# W05 - Salaries by Position

In [1]:
# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Load the salary dataset with the correct date
salaries = pd.read_csv('Salaries_v4_202412161100.csv')
# salaries = pd.read_csv('Salaries_v3_202410141100.csv')
countries_coef = pd.read_csv('countries_salary_coef.csv')
salaries = salaries.drop_duplicates('id').reset_index()
salaries = salaries.drop('index',axis=1)

In [3]:
## Remove the specific rows that can cause inconsistency to the salary dataset
## Salaries_v3_202410141100.csv
# salaries = salaries.drop(17343,axis=0)
## Salaries_v4_202412161100.csv
salaries = salaries.drop([14255,8691,8931],axis=0)

### Initial Info About Dataset

In [4]:
print("#### THIS SALARY DATASET CONTAINS {} ROWS & {} COLUMNS ####".format(salaries.shape[0], salaries.shape[1]))

#### THIS SALARY DATASET CONTAINS 19554 ROWS & 16 COLUMNS ####

In [5]:
salaries.head()

,id,found_country,title,position,employment_type,company,company_score,edu_degrees,edu_degrees_major,working_year,education_score,ms_counts,skill_counts,main_skills,skills,amount_usd
0,0000083c-7054-4a2b-b675-6ac664c66bfb,United States,"Software Developer II at Audible, Inc.",Software Developer II,Full-time,"Audible, Inc.",8.9,"HIGH_SCHOOL,MASTERS,UNDERGRADUATE","Bachelor’s Degree, Computer Science,High Schoo...",11,8.1,21,20,"Ajax, C, C++, CSS, Data Engineering, HTML, HTM...","ajax, c, c++, cascading style sheets (css), cs...",192000
1,00013847-ecf1-4a5a-ba44-16475dc28eba,United States,Retail Associate at Converse,Retail Associate,Full-time,NaN,NaN,UNDERGRADUATE,NaN,5,NaN,14,10,"Communication, Customer Service, Deadline Mana...","communication, customer service, employee trai...",38000
2,00018332-5b5d-4c23-88f8-1c2cdc133e28,United Kingdom,Test Engineer at Sky,Test Engineer,Full-time,NaN,NaN,UNDERGRADUATE,"Bachelor of Science (BSc), Computer Software E...",12,7.0,15,20,"Agile, Attention to Detail, Automated Testing,...","agile methodologies, api testing, communicatio...",66191
3,000c1054-ab28-4c4d-90b0-fa4b1ed31a2a,United States,Hardware Engineer at Google,Hardware Engineer,NaN,Google,8.7,MASTERS,"Master of Science (MS), Computer Engineering",13,8.9,9,20,"C, Circuit Design, Debugging, Embedded Softwar...","asic, c, computer architecture, debugging, emb...",341000
4,00145b03-e286-4bdc-9063-ed5d2095306a,United States,BI Engineer @ Amazon | MS,BIE II,NaN,Amazon,8.4,MASTERS,"Master of Science - MS, Data Analytics",3,8.5,6,9,"JavaScript, Marketing Research, Microsoft Exce...","javascript, microsoft excel, microsoft office,...",185000

In [6]:
salaries.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19554 entries, 0 to 19556
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 19554 non-null  object
 1   found_country      19554 non-null  object
 2   title              19542 non-null  object
 3   position           19554 non-null  object
 4   employment_type    12397 non-null  object
 5   company            16936 non-null  object
 6   company_score      15739 non-null  float64
 7   edu_degrees        19000 non-null  object
 8   edu_degrees_major  18623 non-null  object
 9   working_year       19554 non-null  int64
 10  education_score    14956 non-null  float64
 11  ms_counts          19554 non-null  int64
 12  skill_counts       19554 non-null  int64
 13  main_skills        19554 non-null  object
 14  skills             19554 non-null  object
 15  amount_usd         19554 non-null  int64
dtypes: float64(2), int64(4), object(10)
memory usage: 2.5+ MB

In [7]:
salaries.isnull().sum()

id                      0
found_country           0
title                  12
position                0
employment_type      7157
company              2618
company_score        3815
edu_degrees           554
edu_degrees_major     931
working_year            0
education_score      4598
ms_counts               0
skill_counts            0
main_skills             0
skills                  0
amount_usd              0
dtype: int64

In [8]:
round(salaries.describe(), 3)

,company_score,working_year,education_score,ms_counts,skill_counts,amount_usd
count,15739.000,19554.000,14956.000,19554.000,19554.000,19554.000
mean,8.249,11.450,8.401,15.738,18.778,163366.553
std,0.562,7.213,1.383,7.306,7.815,81118.159
min,3.800,0.000,1.600,1.000,1.000,21000.000
25%,8.100,6.000,7.500,11.000,15.000,102000.000
50%,8.400,10.000,8.600,16.000,20.000,150000.000
75%,8.600,15.000,9.700,20.000,20.000,210000.000
max,10.000,57.000,10.000,56.000,82.000,560000.000

## SALARY INFO BY POSITIONS (HARDCODED)

In [9]:
# Count each identified positions of all rows and collect their salaries
### White collar positions
account_manager_cnt = 0;       account_manager_slr = [];       ai_eng_cnt = 0;                   ai_eng_slr = [];  
application_eng_cnt = 0;       application_eng_slr = [];       automation_test_cnt = 0;          automation_test_slr = [];  
backend_dev_cnt = 0;           backend_dev_slr = [];           business_analyst_cnt = 0;         business_analyst_slr = [];  
business_intel_eng_cnt = 0;    business_intel_eng_slr = [];    chemical_eng_cnt = 0;             chemical_eng_slr = [];  
civil_eng_cnt = 0;             civil_eng_slr = [];             cloud_eng_cnt = 0;                cloud_eng_slr = [];  
consultant_cnt = 0;            consultant_slr = [];            content_designer_cnt = 0;         content_designer_slr = [];  
content_producer_cnt = 0;      content_producer_slr = [];      content_strat_cnt = 0;            content_strat_slr = [];  
customer_eng_cnt = 0;          customer_eng_slr = [];          data_analyst_cnt = 0;             data_analyst_slr = [];  
data_architect_cnt = 0;        data_architect_slr = [];        data_eng_cnt = 0;                 data_eng_slr = [];  
data_scientist_cnt = 0;        data_scientist_slr = [];        db_admin_cnt = 0;                 db_admin_slr = [];  
db_eng_cnt = 0;                db_eng_slr = [];                design_eng_cnt = 0;               design_eng_slr = [];  
devops_eng_cnt = 0;            devops_eng_slr = [];            distinguished_eng_cnt = 0;        distinguished_eng_slr = [];    
ecommerce_cnt = 0;             ecommerce_slr = [];             electrical_eng_cnt = 0;           electrical_eng_slr = [];  
energy_analyst_cnt = 0;        energy_analyst_slr = [];        environmental_eng_cnt = 0;        environmental_eng_slr = [];  
finance_analyst_cnt = 0;       finance_analyst_slr = [];       frontend_dev_cnt = 0;             frontend_dev_slr = [];  
fullstack_dev_cnt = 0;         fullstack_dev_slr = [];         graphic_designer_cnt = 0;         graphic_designer_slr = [];  
hardware_eng_cnt = 0;          hardware_eng_slr = [];          help_desk_sup_cnt = 0;            help_desk_sup_slr = [];  
infrastructure_eng_cnt = 0;    infrastructure_eng_slr = [];    investment_bank_analyst_cnt = 0;  investment_bank_analyst_slr = [];  
it_architect_cnt = 0;          it_architect_slr = [];          it_support_eng_cnt = 0;           it_support_eng_slr = [];  
java_dev_cnt = 0;              java_dev_slr = [];              machine_learning_eng_cnt = 0;     machine_learning_eng_slr = [];    
marketing_analyst_cnt = 0;     marketing_analyst_slr = [];     mechanical_eng_cnt = 0;           mechanical_eng_slr = [];  
mobile_dev_cnt = 0;            mobile_dev_slr = [];            network_admin_cnt = 0;            network_admin_slr = [];  
network_eng_cnt = 0;           network_eng_slr = [];           petroleum_eng_cnt = 0;            petroleum_eng_slr = [];  
platform_eng_cnt = 0;          platform_eng_slr = [];          policy_analyst_cnt = 0;           policy_analyst_slr = [];  
process_eng_cnt = 0;           process_eng_slr = [];           product_designer_cnt = 0;         product_designer_slr = [];  
product_manager_cnt = 0;       product_manager_slr = [];       program_manager_cnt = 0;          program_manager_slr = [];  
project_manager_cnt = 0;       project_manager_slr = [];       python_dev_cnt = 0;               python_dev_slr = [];  
qa_analyst_cnt = 0;            qa_analyst_slr = [];            qa_engineer_cnt = 0;              qa_engineer_slr = [];  
research_eng_cnt = 0;          research_eng_slr = [];          sales_dev_repr_cnt = 0;           sales_dev_repr_slr = [];  
sales_eng_cnt = 0;             sales_eng_slr = [];             salesforce_dev_cnt = 0;           salesforce_dev_slr = [];  
security_eng_cnt = 0;          security_eng_slr = [];          seo_analyst_cnt = 0;              seo_analyst_slr = [];  
service_management_cnt = 0;    service_management_slr = [];    sharepoint_dev_cnt = 0;           sharepoint_dev_slr = [];  
site_reliability_eng_cnt = 0;  site_reliability_eng_slr = [];  software_eng_cnt = 0;             software_eng_slr = [];  
software_qa_eng_cnt = 0;       software_qa_eng_slr = [];       software_test_eng_cnt = 0;        software_test_eng_slr = [];  
solutions_eng_cnt = 0;         solutions_eng_slr = [];         staff_eng_cnt = 0;                staff_eng_slr = [];  
supply_chain_analyst_cnt = 0;  supply_chain_analyst_slr = [];  support_eng_cnt = 0;              support_eng_slr = [];  
system_admin_cnt = 0;          system_admin_slr = [];          system_eng_cnt = 0;               system_eng_slr = [];  
technical_eng_cnt = 0;         technical_eng_slr = [];         ux_ui_designer_cnt = 0;           ux_ui_designer_slr = [];  
web_developer_cnt = 0;         web_developer_slr = [];  
### Blue collar positions
account_executive_cnt = 0;     account_executive_slr = [];     accountant_cnt = 0;               accountant_slr = [];  
actuary_cnt = 0;               actuary_slr = [];               admissions_counselor_cnt = 0;     admissions_counselor_slr = [];  
auditor_cnt = 0;               auditor_slr = [];               barista_cnt = 0;                  barista_slr = [];  
bartender_cnt = 0;             bartender_slr = [];             beauty_advisor_cnt = 0;           beauty_advisor_slr = [];  
boilermaker_cnt = 0;           boilermaker_slr = [];           bookkeeper_cnt = 0;               bookkeeper_slr = [];  
claims_adjuster_cnt = 0;       claims_adjuster_slr = [];       compliance_officer_cnt = 0;       compliance_officer_slr = [];  
corporate_counsel_cnt = 0;     corporate_counsel_slr = [];     curriculum_dev_cnt = 0;           curriculum_dev_slr = [];  
delivery_driver_cnt = 0;       delivery_driver_slr = [];       dental_assistant_cnt = 0;         dental_assistant_slr = [];  
electrician_cnt = 0;           electrician_slr = [];           food_scientist_cnt = 0;           food_scientist_slr = [];  
inside_sales_cnt = 0;          inside_sales_slr = [];          insurance_agent_cnt = 0;          insurance_agent_slr = [];  
legal_secretary_cnt = 0;       legal_secretary_slr = [];       librarian_cnt = 0;                librarian_slr = [];  
medical_assistant_cnt = 0;     medical_assistant_slr = [];     merchandiser_cnt = 0;             merchandiser_slr = [];  
nurse_cnt = 0;                 nurse_slr = [];                 office_admin_cnt = 0;             office_admin_slr = [];  
outside_sales_cnt = 0;         outside_sales_slr = [];         paralegal_cnt = 0;                paralegal_slr = [];  
paramedic_cnt = 0;             paramedic_slr = [];             police_officer_cnt = 0;           police_officer_slr = [];  
principal_cnt = 0;             principal_slr = [];             program_coord_cnt = 0;            program_coord_slr = [];  
real_estate_agent_cnt = 0;     real_estate_agent_slr = [];     recruit_cnt = 0;                  recruit_slr = [];  
retail_sales_cnt = 0;          retail_sales_slr = [];          sales_associate_cnt = 0;          sales_associate_slr = [];  
school_counselor_cnt = 0;      school_counselor_slr = [];      school_psychologist_cnt = 0;      school_psychologist_slr = [];  
security_officer_cnt = 0;      security_officer_slr = [];      social_worker_cnt = 0;            social_worker_slr = [];  
supervisor_cnt = 0;            supervisor_slr = [];            talent_assistant_cnt = 0;         talent_assistant_slr = [];  
tax_advisor_cnt = 0;           tax_advisor_slr = [];           teacher_cnt = 0;                  teacher_slr = [];  
technician_cnt = 0;            technician_slr = [];            therapist_cnt = 0;                therapist_slr = [];  
touring_assistant_cnt = 0;     touring_assistant_slr = [];     transport_planner_cnt = 0;        transport_planner_slr = [];  
underwriter_cnt = 0;           underwriter_slr = [];           urban_planner_cnt = 0;            urban_planner_slr = [];  
vice_president_cnt = 0;        vice_president_slr = [];        welder_cnt = 0;                   welder_slr = [];  
### Other non-fitting positions
analyst_cnt = 0;               analyst_slr = [];               developer_cnt = 0;                developer_slr = [];  
engineer_cnt = 0;              engineer_slr = [];              server_cnt = 0;                   server_slr = [];  
assistant_cnt = 0;             assistant_slr = [];  
### Uncategorized positions and their numbers
uncategorized_pos_cnt = 0;     uncategorized_pos_slr = [];     uncategorized_pos = [];

all_positions = salaries['position'].values
all_salaries = salaries['amount_usd'].values
for i in range(len(all_positions)):
    pos = all_positions[i];   salary = all_salaries[i];
    pos = pos.lower().replace('&','and')
    ### WHITE COLLAR POSITIONS ###
    if 'account manager' in pos:   
        account_manager_cnt += 1;   account_manager_slr.append(salary);
    elif 'ai engineer' in pos or 'ai frameworks engineer' in pos:   
        ai_eng_cnt += 1;   ai_eng_slr.append(salary);
    elif 'application engineer' in pos or 'applications engineer' in pos or 'application developer' in pos:   
        application_eng_cnt += 1;   application_eng_slr.append(salary);
    elif 'automation test' in pos:   
        automation_test_cnt += 1;   automation_test_slr.append(salary);
    elif 'backend developer' in pos or 'back end developer' in pos:   
        backend_dev_cnt += 1;   backend_dev_slr.append(salary);
    elif 'business analyst' in pos or 'business intelligence analyst' in pos or 'business systems analyst' in pos \
      or 'business system analyst' in pos or 'business operations analyst' in pos or 'business tech analyst' in pos \
      or 'business technology analyst' in pos or 'business practice analyst' in pos or 'analyst.business' in pos \
      or 'business strategy analyst' in pos or 'business  analyst' in pos or 'business process analyst' in pos \
      or 'business management program analyst' in pos or 'business integrity analyst' in pos or 'analyst, business' in pos:
        business_analyst_cnt += 1;   business_analyst_slr.append(salary);
    elif 'business intelligence engineer' in pos or 'bi engineer' in pos or 'business intelligence developer' in pos \
      or 'business intelligence lead engineer' in pos or 'business intelligence and analytics engineer' in pos \
      or 'bie' in pos:
        business_intel_eng_cnt += 1;   business_intel_eng_slr.append(salary);
    elif 'chemical engineer' in pos:   
        chemical_eng_cnt += 1;   chemical_eng_slr.append(salary);
    elif 'civil engineer' in pos:   
        civil_eng_cnt += 1;   civil_eng_slr.append(salary);
    elif 'cloud engineer' in pos or 'cloud deployment engineer' in pos or 'cloud and innovation engineer' in pos:
        cloud_eng_cnt += 1;   cloud_eng_slr.append(salary);
    elif 'consultant' in pos:   
        consultant_cnt += 1;   consultant_slr.append(salary);
    elif 'content designer' in pos:   
        content_designer_cnt += 1;   content_designer_slr.append(salary);
    elif 'content producer' in pos:   
        content_producer_cnt += 1;   content_producer_slr.append(salary);
    elif 'content strategist' in pos:   
        content_strat_cnt += 1;   content_strat_slr.append(salary);
    elif 'customer engineer' in pos:   
        customer_eng_cnt += 1;   customer_eng_slr.append(salary);
    elif 'data analyst' in pos or 'data analytics and reporting analyst' in pos or 'data systems analyst' in pos \
      or 'data science analyst' in pos or 'data intelligence analyst' in pos or 'data quality analyst' in pos \
      or 'data operations analyst' in pos or 'data governance analyst' in pos or 'data protection analyst' in pos \
      or 'data center analyst' in pos or 'data security analyst' in pos or 'data integrity analyst' in pos \
      or 'data and reporting analyst' in pos or 'data and compliance analyst' in pos or 'data insights analyst' in pos \
      or 'data reference analyst' in pos or 'analyst, data' in pos or 'analyst - data' in pos \
      or 'data quality and sales operations analyst' in pos or ('analyst' in pos and 'data' in pos):
        data_analyst_cnt += 1;   data_analyst_slr.append(salary);
    elif 'data architect' in pos:   
        data_architect_cnt += 1;   data_architect_slr.append(salary);
    elif 'data engineer' in pos:   
        data_eng_cnt += 1;   data_eng_slr.append(salary);
    elif 'data scientist' in pos or 'data and applied scientist' in pos or 'applied scientist' in pos \
      or 'data and systems analyst' in pos or 'data science engineer' in pos or 'data science and engineering' in pos:
        data_scientist_cnt += 1;   data_scientist_slr.append(salary);
    elif 'database administrator' in pos or 'database administration' in pos:   
        db_admin_cnt += 1;   db_admin_slr.append(salary);
    elif 'database engineer' in pos:   
        db_eng_cnt += 1;   db_eng_slr.append(salary);
    elif 'design engineer' in pos or 'design verification engineer' in pos:   
        design_eng_cnt += 1;   design_eng_slr.append(salary);
    elif 'devops engineer' in pos or 'devsecops' in pos or 'devops' in pos:   
        devops_eng_cnt += 1;   devops_eng_slr.append(salary);
    elif 'distinguished engineer' in pos:   
        distinguished_eng_cnt += 1;   distinguished_eng_slr.append(salary);
    elif 'ecommerce' in pos or 'e-commerce' in pos:   
        ecommerce_cnt += 1;   ecommerce_slr.append(salary);
    elif 'electrical engineer' in pos:   
        electrical_eng_cnt += 1;   electrical_eng_slr.append(salary);
    elif 'energy analyst' in pos or 'energy markets analyst' in pos:   
        energy_analyst_cnt += 1;   energy_analyst_slr.append(salary);
    elif 'environmental engineer' in pos or 'environmental compliance engineer' in pos \
      or 'environmental consulting engineer' in pos:
        environmental_eng_cnt += 1;   environmental_eng_slr.append(salary);
    elif 'financial analyst' in pos or 'finance operations analyst' in pos or 'finance project analyst' in pos \
      or 'finance analyst' in pos:   
        finance_analyst_cnt += 1;   finance_analyst_slr.append(salary);
    elif 'frontend developer' in pos or 'front-end developer' in pos or 'front end developer' in pos \
      or 'frontend engineer' in pos or 'front-end engineer' in pos or 'front end engineer' in pos or 'react developer' in pos:
        frontend_dev_cnt += 1;   frontend_dev_slr.append(salary);
    elif 'fullstack developer' in pos or 'full stack developer' in pos or 'full-stack developer' in pos \
      or 'fullstack engineer' in pos or 'full stack engineer' in pos or 'full-stack javascript developer' in pos \
      or 'full-stack react native developer' in pos:   
        fullstack_dev_cnt += 1;   fullstack_dev_slr.append(salary);
    elif 'graphic designer' in pos:   
        graphic_designer_cnt += 1;   graphic_designer_slr.append(salary);
    elif 'hardware engineer' in pos or 'hardware dev engineer' in pos or 'hardware development engineer' in pos:
        hardware_eng_cnt += 1;   hardware_eng_slr.append(salary);
    elif 'help desk' in pos or 'helpdesk' in pos:   
        help_desk_sup_cnt += 1;   help_desk_sup_slr.append(salary);
    elif 'infrastructure engineer' in pos:   
        infrastructure_eng_cnt += 1;   infrastructure_eng_slr.append(salary);
    elif 'investment banking analyst' in pos:   
        investment_bank_analyst_cnt += 1;   investment_bank_analyst_slr.append(salary);
    elif 'it architect' in pos or 'information technology architect' in pos:   
        it_architect_cnt += 1;   it_architect_slr.append(salary);
    elif 'it support engineer' in pos or 'it engineer' in pos or 'information technology engineer' in pos \
      or 'information technology operations engineer' in pos or 'information architect' in pos:   
        it_support_eng_cnt += 1;   it_support_eng_slr.append(salary);
    elif 'java developer' in pos or 'java/j2ee developer' in pos:   
        java_dev_cnt += 1;   java_dev_slr.append(salary);
    elif 'machine learning engineer' in pos or 'machine learning scientist' in pos \
      or 'machine learning research engineer' in pos or 'machine learning and relevance engineer' in pos \
      or 'machine learning platform engineer' in pos or 'machine learning developer' in pos or 'deep learning/machine learning' in pos \
      or 'ml engineer' in pos or 'machine learning' in pos:
        machine_learning_eng_cnt += 1;   machine_learning_eng_slr.append(salary);
    elif 'marketing analyst' in pos or 'market analyst' in pos or 'market research and analysis' in pos \
      or 'market research manager' in pos or 'marketing operations analyst' in pos or 'market research analyst' in pos \
      or 'marketing execution analyst' in pos or 'marketing research analyst' in pos or 'marketing campaign analyst' in pos \
      or 'analyst, marketing' in pos:   
        marketing_analyst_cnt += 1;   marketing_analyst_slr.append(salary);
    elif 'mechanical engineer' in pos:   
        mechanical_eng_cnt += 1;   mechanical_eng_slr.append(salary);
    elif 'mobile developer' in pos or 'ios developer' in pos or 'ios engineer' in pos or 'ios/tvos engineer' in pos \
      or 'android developer' in pos or 'android engineer' in pos:
        mobile_dev_cnt += 1;   mobile_dev_slr.append(salary);
    elif 'network administrator' in pos or 'network systems administrator' in pos:   
        network_admin_cnt += 1;   network_admin_slr.append(salary);
    elif 'network engineer' in pos or 'network support engineer' in pos or 'network development engineer' in pos \
      or 'network consulting engineer' in pos:
        network_eng_cnt += 1;   network_eng_slr.append(salary);
    elif 'petroleum engineer' in pos:   
        petroleum_eng_cnt += 1;   petroleum_eng_slr.append(salary);
    elif 'platform engineer' in pos:   
        platform_eng_cnt += 1;   platform_eng_slr.append(salary);
    elif 'policy analyst' in pos:   
        policy_analyst_cnt += 1;   policy_analyst_slr.append(salary);
    elif 'process engineer' in pos:   
        process_eng_cnt += 1;   process_eng_slr.append(salary);
    elif 'product designer' in pos or 'production engineer' in pos or 'product development engineer' in pos:
        product_designer_cnt += 1;   product_designer_slr.append(salary);
    elif 'product manager' in pos or 'product engineering manager' in pos:   
        product_manager_cnt += 1;   product_manager_slr.append(salary);
    elif 'program manager' in pos or 'program mgmt manager' in pos:   
        program_manager_cnt += 1;   program_manager_slr.append(salary);
    elif 'project manager' in pos or 'project mananger' in pos:   
        project_manager_cnt += 1;   project_manager_slr.append(salary);
    elif 'python developer' in pos:   
        python_dev_cnt += 1;   python_dev_slr.append(salary);
    elif 'quality assurance analyst' in pos or 'qa analyst' in pos:   
        qa_analyst_cnt += 1;   qa_analyst_slr.append(salary);
    elif 'quality assurance engineer' in pos or 'quality assurance specialist' in pos or 'quality engineer' in pos \
      or 'qa automation engineer' in pos or 'quality assurance automation engineer' in pos or 'qa tester engineer' in pos:
        qa_engineer_cnt += 1;   qa_engineer_slr.append(salary);
    elif 'research engineer' in pos or 'research scientist' in pos:   
        research_eng_cnt += 1;   research_eng_slr.append(salary);
    elif 'sales development representative' in pos:   
        sales_dev_repr_cnt += 1;   sales_dev_repr_slr.append(salary);
    elif 'sales engineer' in pos:   
        sales_eng_cnt += 1;   sales_eng_slr.append(salary);
    elif 'salesforce developer' in pos or 'salesforce admin and developer' in pos:   
        salesforce_dev_cnt += 1;   salesforce_dev_slr.append(salary);
    elif 'security engineer' in pos:   
        security_eng_cnt += 1;   security_eng_slr.append(salary);
    elif 'seo analyst' in pos or 'search engine optimization analyst' in pos or 'search engine optimization specialist' in pos:
        seo_analyst_cnt += 1;   seo_analyst_slr.append(salary);
    elif 'service management' in pos:   
        service_management_cnt += 1;   service_management_slr.append(salary);
    elif 'sharepoint developer' in pos:   
        sharepoint_dev_cnt += 1;   sharepoint_dev_slr.append(salary);
    elif 'site reliability engineer' in pos:   
        site_reliability_eng_cnt += 1;   site_reliability_eng_slr.append(salary);
    elif 'software qa engineer' in pos or 'qa engineer' in pos:   
        software_qa_eng_cnt += 1;   software_qa_eng_slr.append(salary);
    elif 'software developer' in pos or 'software engineer' in pos or 'software development engineer' in pos \
      or 'software dev engineer' in pos or 'software analyst and developer' in pos or 'softwear developer' in pos \
      or 'engineer software' in pos or 'software firmware engineer' in pos or 'software  engineer' in pos \
      or 'software graphics engineer' in pos or 'firmware engineer' in pos or 'firmware development engineer' in pos \
      or 'software application development engineer' in pos or 'software build engineer' in pos \
      or 'software devlopment engineer' in pos:   
        software_eng_cnt += 1;   software_eng_slr.append(salary);
    elif 'software test engineer' in pos or 'test engineer' in pos or 'test automation engineer' in pos \
      or 'test product development engineer' in pos or 'test technology engineer' in pos or 'test r and d engineer' in pos \
      or 'software test' in pos:
        software_test_eng_cnt += 1;   software_test_eng_slr.append(salary);
    elif 'solutions engineer' in pos or 'solution engineer' in pos or 'solutions architect' in pos or 'solution architect' in pos:
        solutions_eng_cnt += 1;   solutions_eng_slr.append(salary);
    elif 'staff engineer' in pos:   
        staff_eng_cnt += 1;   staff_eng_slr.append(salary);
    elif 'supply chain analyst' in pos or 'supply chain solutions analyst' in pos or 'supply chain planning analyst' in pos \
      or 'supply chain associate analyst' in pos or 'supply chain program analyst' in pos or 'supply chain procurement analyst' in pos \
      or 'supply chain planning, mrp analyst' in pos:
        supply_chain_analyst_cnt += 1;   supply_chain_analyst_slr.append(salary);
    elif 'support engineer' in pos or 'technical support engineer' in pos:   
        support_eng_cnt += 1;   support_eng_slr.append(salary);
    elif 'system administrator' in pos:   
        system_admin_cnt += 1;   system_admin_slr.append(salary);
    elif 'system engineer' in pos or 'systems engineer' in pos or 'systems admin/engineer' in pos \
      or 'system development engineer' in pos or 'system admin/engineer' in pos or 'systems development engineer' in pos:
        system_eng_cnt += 1;   system_eng_slr.append(salary);
    elif 'technical engineer' in pos or 'technical analyst' in pos or 'technical solution analyst' in pos \
      or 'technical solutions analyst' in pos:
        technical_eng_cnt += 1;   technical_eng_slr.append(salary);
    elif 'user experience designer' in pos or 'ux designer' in pos or 'interaction designer (ux)' in pos \
      or 'ux/ui designer' in pos or 'ux engineer' in pos or 'ui developer' in pos or 'user experience engineer' in pos \
      or 'ux researcher' in pos:
        ux_ui_designer_cnt += 1;   ux_ui_designer_slr.append(salary);
    elif 'web developer' in pos or 'web production developer' in pos or 'website developer' in pos \
      or 'web solutions engineer' in pos or 'web apps' in pos:
        web_developer_cnt += 1;   web_developer_slr.append(salary);
    ### BLUE COLLAR POSITIONS ###
    elif 'account executive' in pos:   
        account_executive_cnt += 1;   account_executive_slr.append(salary);
    elif 'accountant' in pos:   
        accountant_cnt += 1;   accountant_slr.append(salary);
    elif 'actuary' in pos:   
        actuary_cnt += 1;   actuary_slr.append(salary);
    elif 'admission counselor' in pos or 'admissions counselor' in pos:   
        admissions_counselor_cnt += 1;   admissions_counselor_slr.append(salary);
    elif 'auditor' in pos:   
        auditor_cnt += 1;   auditor_slr.append(salary);
    elif 'barista' in pos:   
        barista_cnt += 1;   barista_slr.append(salary);
    elif 'bartender' in pos:   
        bartender_cnt += 1;   bartender_slr.append(salary);
    elif 'beauty advisor' in pos:   
        beauty_advisor_cnt += 1;   beauty_advisor_slr.append(salary);
    elif 'boilermaker' in pos:   
        boilermaker_cnt += 1;   boilermaker_slr.append(salary);
    elif 'bookkeeper' in pos:   
        bookkeeper_cnt += 1;   bookkeeper_slr.append(salary);
    elif 'claims adjuster' in pos:   
        claims_adjuster_cnt += 1;   claims_adjuster_slr.append(salary);
    elif 'compliance officer' in pos or 'compliance business control officer' in pos:   
        compliance_officer_cnt += 1;   compliance_officer_slr.append(salary);
    elif 'corporate counsel' in pos:   
        corporate_counsel_cnt += 1;   corporate_counsel_slr.append(salary);
    elif 'curriculum developer' in pos:   
        curriculum_dev_cnt += 1;   curriculum_dev_slr.append(salary);
    elif 'delivery driver' in pos:   
        delivery_driver_cnt += 1;   delivery_driver_slr.append(salary);
    elif 'dental assistant' in pos:   
        dental_assistant_cnt += 1;   dental_assistant_slr.append(salary);
    elif 'electrician' in pos:   
        electrician_cnt += 1;   electrician_slr.append(salary);
    elif 'food scientist' in pos:   
        food_scientist_cnt += 1;   food_scientist_slr.append(salary);
    elif 'inside sales' in pos:   
        inside_sales_cnt += 1;   inside_sales_slr.append(salary);
    elif 'insurance agent' in pos:   
        insurance_agent_cnt += 1;   insurance_agent_slr.append(salary);
    elif 'legal secretary' in pos:   
        legal_secretary_cnt += 1;   legal_secretary_slr.append(salary);
    elif 'librarian' in pos:   
        librarian_cnt += 1;   librarian_slr.append(salary);
    elif 'medical assistant' in pos:   
        medical_assistant_cnt += 1;   medical_assistant_slr.append(salary);
    elif 'merchandiser' in pos:   
        merchandiser_cnt += 1;   merchandiser_slr.append(salary);
    elif 'nurse' in pos:   
        nurse_cnt += 1;   nurse_slr.append(salary);
    elif 'office administrator' in pos:   
        office_admin_cnt += 1;   office_admin_slr.append(salary);
    elif 'outside sales' in pos:   
        outside_sales_cnt += 1;   outside_sales_slr.append(salary);
    elif 'paralegal' in pos:   
        paralegal_cnt += 1;   paralegal_slr.append(salary);
    elif 'paramedic' in pos:   
        paramedic_cnt += 1;   paramedic_slr.append(salary);
    elif 'police officer' in pos:   
        police_officer_cnt += 1;   police_officer_slr.append(salary);
    elif 'principal' in pos:   
        principal_cnt += 1;   principal_slr.append(salary);
    elif 'program coordinator' in pos:   
        program_coord_cnt += 1;   program_coord_slr.append(salary);
    elif 'real estate agent' in pos:   
        real_estate_agent_cnt += 1;   real_estate_agent_slr.append(salary);
    elif 'recruit' in pos:   
        recruit_cnt += 1;   recruit_slr.append(salary);
    elif 'retail sales' in pos:   
        retail_sales_cnt += 1;   retail_sales_slr.append(salary);
    elif 'sales associate' in pos:   
        sales_associate_cnt += 1;   sales_associate_slr.append(salary);
    elif 'school counselor' in pos:   
        school_counselor_cnt += 1;   school_counselor_slr.append(salary);
    elif 'school psychologist' in pos:   
        school_psychologist_cnt += 1;   school_psychologist_slr.append(salary);
    elif 'security officer' in pos or 'security guard' in pos:   
        security_officer_cnt += 1;   security_officer_slr.append(salary);
    elif 'social worker' in pos:   
        social_worker_cnt += 1;   social_worker_slr.append(salary);
    elif 'supervisor' in pos:   
        supervisor_cnt += 1;   supervisor_slr.append(salary);
    elif 'talent assistant' in pos or 'assistant, talent' in pos:   
        talent_assistant_cnt += 1;   talent_assistant_slr.append(salary);
    elif 'tax advisor' in pos:   
        tax_advisor_cnt += 1;   tax_advisor_slr.append(salary);
    elif 'teacher' in pos:   
        teacher_cnt += 1;   teacher_slr.append(salary);
    elif 'technician' in pos:   
        technician_cnt += 1;   technician_slr.append(salary);
    elif 'therapist' in pos:   
        therapist_cnt += 1;   therapist_slr.append(salary);
    elif 'touring assistant' in pos or ('touring' in pos and 'assistant' in pos):   
        touring_assistant_cnt += 1;   touring_assistant_slr.append(salary);
    elif 'transportation planner' in pos:   
        transport_planner_cnt += 1;   transport_planner_slr.append(salary);
    elif 'underwriter' in pos:   
        underwriter_cnt += 1;   underwriter_slr.append(salary);
    elif 'urban planner' in pos:   
        urban_planner_cnt += 1;   urban_planner_slr.append(salary);
    elif 'vice president' in pos:   
        vice_president_cnt += 1;   vice_president_slr.append(salary);
    elif 'welder' in pos:   
        welder_cnt += 1;   welder_slr.append(salary);
    ### Other non-fitting positions ###
    elif 'analyst' in pos:     analyst_cnt += 1;     analyst_slr.append(salary);
    elif 'developer' in pos:   developer_cnt += 1;   developer_slr.append(salary);
    elif 'engineer' in pos:    engineer_cnt += 1;    engineer_slr.append(salary);
    elif 'server' in pos:      server_cnt += 1;      server_slr.append(salary);
    elif 'assistant' in pos:   assistant_cnt += 1;   assistant_slr.append(salary);
    else:   
        uncategorized_pos_cnt += 1;   uncategorized_pos_slr.append(salary);   uncategorized_pos.append(pos);  

print("####### WHITE COLLAR POSITIONS ############## AVG ######## MIN ######## MAX ######")
print("{:4} ACCOUNT MANAGER                    | {:10.2f} | {:10.2f} | {:10.2f}".format(account_manager_cnt, 
    np.array(account_manager_slr).mean(), np.array(account_manager_slr).min(), np.array(account_manager_slr).max()))
print("{:4} AI ENGINEER                        | {:10.2f} | {:10.2f} | {:10.2f}".format(ai_eng_cnt, 
    np.array(ai_eng_slr).mean(), np.array(ai_eng_slr).min(), np.array(ai_eng_slr).max()))
print("{:4} APPLICATION ENGINEER / DEVELOPER   | {:10.2f} | {:10.2f} | {:10.2f}".format(application_eng_cnt, 
    np.array(application_eng_slr).mean(), np.array(application_eng_slr).min(), np.array(application_eng_slr).max()))
print("{:4} AUTOMATION TESTER                  | {:10.2f} | {:10.2f} | {:10.2f}".format(automation_test_cnt, 
    np.array(automation_test_slr).mean(), np.array(automation_test_slr).min(), np.array(automation_test_slr).max()))
print("{:4} BACKEND DEVELOPER                  | {:10.2f} | {:10.2f} | {:10.2f}".format(backend_dev_cnt, 
    np.array(backend_dev_slr).mean(), np.array(backend_dev_slr).min(), np.array(backend_dev_slr).max()))
print("{:4} BUSINESS ANALYST                   | {:10.2f} | {:10.2f} | {:10.2f}".format(business_analyst_cnt, 
    np.array(business_analyst_slr).mean(), np.array(business_analyst_slr).min(), np.array(business_analyst_slr).max()))
print("{:4} BUSINESS INT. ENGINEER / DEVELOPER | {:10.2f} | {:10.2f} | {:10.2f}".format(business_intel_eng_cnt, 
    np.array(business_intel_eng_slr).mean(), np.array(business_intel_eng_slr).min(), np.array(business_intel_eng_slr).max()))
print("{:4} CHEMICAL ENGINEER                  | {:10.2f} | {:10.2f} | {:10.2f}".format(chemical_eng_cnt, 
    np.array(chemical_eng_slr).mean(), np.array(chemical_eng_slr).min(), np.array(chemical_eng_slr).max()))
print("{:4} CIVIL ENGINEER                     | {:10.2f} | {:10.2f} | {:10.2f}".format(civil_eng_cnt, 
    np.array(civil_eng_slr).mean(), np.array(civil_eng_slr).min(), np.array(civil_eng_slr).max()))
print("{:4} CLOUD ENGINEER                     | {:10.2f} | {:10.2f} | {:10.2f}".format(cloud_eng_cnt, 
    np.array(cloud_eng_slr).mean(), np.array(cloud_eng_slr).min(), np.array(cloud_eng_slr).max()))
print("{:4} CONSULTANT                         | {:10.2f} | {:10.2f} | {:10.2f}".format(consultant_cnt, 
    np.array(consultant_slr).mean(), np.array(consultant_slr).min(), np.array(consultant_slr).max()))
print("{:4} CONTENT DESIGNER                   | {:10.2f} | {:10.2f} | {:10.2f}".format(content_designer_cnt, 
    np.array(content_designer_slr).mean(), np.array(content_designer_slr).min(), np.array(content_designer_slr).max()))
print("{:4} CONTENT PRODUCER                   | {:10.2f} | {:10.2f} | {:10.2f}".format(content_producer_cnt, 
    np.array(content_producer_slr).mean(), np.array(content_producer_slr).min(), np.array(content_producer_slr).max()))
print("{:4} CONTENT STRATEGIST                 | {:10.2f} | {:10.2f} | {:10.2f}".format(content_strat_cnt, 
    np.array(content_strat_slr).mean(), np.array(content_strat_slr).min(), np.array(content_strat_slr).max()))
print("{:4} CUSTOMER ENGINEER                  | {:10.2f} | {:10.2f} | {:10.2f}".format(customer_eng_cnt, 
    np.array(customer_eng_slr).mean(), np.array(customer_eng_slr).min(), np.array(customer_eng_slr).max()))
print("{:4} DATA ANALYST                       | {:10.2f} | {:10.2f} | {:10.2f}".format(data_analyst_cnt, 
    np.array(data_analyst_slr).mean(), np.array(data_analyst_slr).min(), np.array(data_analyst_slr).max()))
print("{:4} DATA ARCHITECT                     | {:10.2f} | {:10.2f} | {:10.2f}".format(data_architect_cnt, 
    np.array(data_architect_slr).mean(), np.array(data_architect_slr).min(), np.array(data_architect_slr).max()))
print("{:4} DATA ENGINEER                      | {:10.2f} | {:10.2f} | {:10.2f}".format(data_eng_cnt, 
    np.array(data_eng_slr).mean(), np.array(data_eng_slr).min(), np.array(data_eng_slr).max()))
print("{:4} DATA SCIENTIST                     | {:10.2f} | {:10.2f} | {:10.2f}".format(data_scientist_cnt, 
    np.array(data_scientist_slr).mean(), np.array(data_scientist_slr).min(), np.array(data_scientist_slr).max()))
print("{:4} DATABASE ADMINISTRATOR             | {:10.2f} | {:10.2f} | {:10.2f}".format(db_admin_cnt, 
    np.array(db_admin_slr).mean(), np.array(db_admin_slr).min(), np.array(db_admin_slr).max()))
print("{:4} DATABASE ENGINEER                  | {:10.2f} | {:10.2f} | {:10.2f}".format(db_eng_cnt, 
    np.array(db_eng_slr).mean(), np.array(db_eng_slr).min(), np.array(db_eng_slr).max()))
print("{:4} DESIGN ENGINEER                    | {:10.2f} | {:10.2f} | {:10.2f}".format(design_eng_cnt, 
    np.array(design_eng_slr).mean(), np.array(design_eng_slr).min(), np.array(design_eng_slr).max()))
print("{:4} DEVOPS ENGINEER                    | {:10.2f} | {:10.2f} | {:10.2f}".format(devops_eng_cnt, 
    np.array(devops_eng_slr).mean(), np.array(devops_eng_slr).min(), np.array(devops_eng_slr).max()))
print("{:4} DISTINGUISED ENGINEER              | {:10.2f} | {:10.2f} | {:10.2f}".format(distinguished_eng_cnt, 
    np.array(distinguished_eng_slr).mean(), np.array(distinguished_eng_slr).min(), np.array(distinguished_eng_slr).max()))
print("{:4} E-COMMERCE                         | {:10.2f} | {:10.2f} | {:10.2f}".format(ecommerce_cnt, 
    np.array(ecommerce_slr).mean(), np.array(ecommerce_slr).min(), np.array(ecommerce_slr).max()))
print("{:4} ELECTRICAL ENGINEER                | {:10.2f} | {:10.2f} | {:10.2f}".format(electrical_eng_cnt, 
    np.array(electrical_eng_slr).mean(), np.array(electrical_eng_slr).min(), np.array(electrical_eng_slr).max()))
print("{:4} ENERGY ANALYST                     | {:10.2f} | {:10.2f} | {:10.2f}".format(energy_analyst_cnt, 
    np.array(energy_analyst_slr).mean(), np.array(energy_analyst_slr).min(), np.array(energy_analyst_slr).max()))
print("{:4} ENVIRONMENTAL ENGINEER             | {:10.2f} | {:10.2f} | {:10.2f}".format(environmental_eng_cnt, 
    np.array(environmental_eng_slr).mean(), np.array(environmental_eng_slr).min(), np.array(environmental_eng_slr).max()))
print("{:4} FINANCIAL ANALYST                  | {:10.2f} | {:10.2f} | {:10.2f}".format(finance_analyst_cnt, 
    np.array(finance_analyst_slr).mean(), np.array(finance_analyst_slr).min(), np.array(finance_analyst_slr).max()))
print("{:4} FRONTEND DEVELOPER                 | {:10.2f} | {:10.2f} | {:10.2f}".format(frontend_dev_cnt, 
    np.array(frontend_dev_slr).mean(), np.array(frontend_dev_slr).min(), np.array(frontend_dev_slr).max()))
print("{:4} FULLSTACK DEVELOPER                | {:10.2f} | {:10.2f} | {:10.2f}".format(fullstack_dev_cnt, 
    np.array(fullstack_dev_slr).mean(), np.array(fullstack_dev_slr).min(), np.array(fullstack_dev_slr).max()))
print("{:4} GRAPHIC DESIGNER                   | {:10.2f} | {:10.2f} | {:10.2f}".format(graphic_designer_cnt, 
    np.array(graphic_designer_slr).mean(), np.array(graphic_designer_slr).min(), np.array(graphic_designer_slr).max()))
print("{:4} HARDWARE ENGINEER                  | {:10.2f} | {:10.2f} | {:10.2f}".format(hardware_eng_cnt, 
    np.array(hardware_eng_slr).mean(), np.array(hardware_eng_slr).min(), np.array(hardware_eng_slr).max()))
print("{:4} HELP DESK SUPPORT TECHNICIAN       | {:10.2f} | {:10.2f} | {:10.2f}".format(help_desk_sup_cnt, 
    np.array(help_desk_sup_slr).mean(), np.array(help_desk_sup_slr).min(), np.array(help_desk_sup_slr).max()))
print("{:4} INFRASTRUCTURE ENGINEER            | {:10.2f} | {:10.2f} | {:10.2f}".format(infrastructure_eng_cnt, 
    np.array(infrastructure_eng_slr).mean(), np.array(infrastructure_eng_slr).min(), np.array(infrastructure_eng_slr).max()))
print("{:4} INVESTMENT BANKING ANALYST         | {:10.2f} | {:10.2f} | {:10.2f}".format(investment_bank_analyst_cnt, 
    np.array(investment_bank_analyst_slr).mean(), np.array(investment_bank_analyst_slr).min(), np.array(investment_bank_analyst_slr).max()))
print("{:4} IT ARCHITECT                       | {:10.2f} | {:10.2f} | {:10.2f}".format(it_architect_cnt, 
    np.array(it_architect_slr).mean(), np.array(it_architect_slr).min(), np.array(it_architect_slr).max()))
print("{:4} IT SUPPORT ENGINEER                | {:10.2f} | {:10.2f} | {:10.2f}".format(it_support_eng_cnt, 
    np.array(it_support_eng_slr).mean(), np.array(it_support_eng_slr).min(), np.array(it_support_eng_slr).max()))
print("{:4} JAVA DEVELOPER                     | {:10.2f} | {:10.2f} | {:10.2f}".format(java_dev_cnt, 
    np.array(java_dev_slr).mean(), np.array(java_dev_slr).min(), np.array(java_dev_slr).max()))
print("{:4} MACHINE LEARNING ENGINEER          | {:10.2f} | {:10.2f} | {:10.2f}".format(machine_learning_eng_cnt, 
    np.array(machine_learning_eng_slr).mean(), np.array(machine_learning_eng_slr).min(), np.array(machine_learning_eng_slr).max()))
print("{:4} MARKETING ANALYST                  | {:10.2f} | {:10.2f} | {:10.2f}".format(marketing_analyst_cnt, 
    np.array(marketing_analyst_slr).mean(), np.array(marketing_analyst_slr).min(), np.array(marketing_analyst_slr).max()))
print("{:4} MECHANICAL ENGINEER                | {:10.2f} | {:10.2f} | {:10.2f}".format(mechanical_eng_cnt, 
    np.array(mechanical_eng_slr).mean(), np.array(mechanical_eng_slr).min(), np.array(mechanical_eng_slr).max()))
print("{:4} MOBILE DEVELOPER                   | {:10.2f} | {:10.2f} | {:10.2f}".format(mobile_dev_cnt, 
    np.array(mobile_dev_slr).mean(), np.array(mobile_dev_slr).min(), np.array(mobile_dev_slr).max()))
print("{:4} NETWORK ADMINISTRATOR              | {:10.2f} | {:10.2f} | {:10.2f}".format(network_admin_cnt, 
    np.array(network_admin_slr).mean(), np.array(network_admin_slr).min(), np.array(network_admin_slr).max()))
print("{:4} NETWORK ENGINEER                   | {:10.2f} | {:10.2f} | {:10.2f}".format(network_eng_cnt, 
    np.array(network_eng_slr).mean(), np.array(network_eng_slr).min(), np.array(network_eng_slr).max()))
print("{:4} PETROLEUM ENGINEER                 | {:10.2f} | {:10.2f} | {:10.2f}".format(petroleum_eng_cnt, 
    np.array(petroleum_eng_slr).mean(), np.array(petroleum_eng_slr).min(), np.array(petroleum_eng_slr).max()))
print("{:4} PLATFORM ENGINEER                  | {:10.2f} | {:10.2f} | {:10.2f}".format(platform_eng_cnt, 
    np.array(platform_eng_slr).mean(), np.array(platform_eng_slr).min(), np.array(platform_eng_slr).max()))
print("{:4} POLICY ANALYST                     | {:10.2f} | {:10.2f} | {:10.2f}".format(policy_analyst_cnt, 
    np.array(policy_analyst_slr).mean(), np.array(policy_analyst_slr).min(), np.array(policy_analyst_slr).max()))
print("{:4} PROCESS ENGINEER                   | {:10.2f} | {:10.2f} | {:10.2f}".format(process_eng_cnt, 
    np.array(process_eng_slr).mean(), np.array(process_eng_slr).min(), np.array(process_eng_slr).max()))
print("{:4} PRODUCT DESIGNER / ENGINEER        | {:10.2f} | {:10.2f} | {:10.2f}".format(product_designer_cnt, 
    np.array(product_designer_slr).mean(), np.array(product_designer_slr).min(), np.array(product_designer_slr).max()))
print("{:4} PRODUCT MANAGER                    | {:10.2f} | {:10.2f} | {:10.2f}".format(product_manager_cnt, 
    np.array(product_manager_slr).mean(), np.array(product_manager_slr).min(), np.array(product_manager_slr).max()))
print("{:4} PROGRAM MANAGER                    | {:10.2f} | {:10.2f} | {:10.2f}".format(program_manager_cnt, 
    np.array(program_manager_slr).mean(), np.array(program_manager_slr).min(), np.array(program_manager_slr).max()))
print("{:4} PROJECT MANAGER                    | {:10.2f} | {:10.2f} | {:10.2f}".format(project_manager_cnt, 
    np.array(project_manager_slr).mean(), np.array(project_manager_slr).min(), np.array(project_manager_slr).max()))
print("{:4} PYTHON DEVELOPER                   | {:10.2f} | {:10.2f} | {:10.2f}".format(python_dev_cnt, 
    np.array(python_dev_slr).mean(), np.array(python_dev_slr).min(), np.array(python_dev_slr).max()))
print("{:4} QUALITY ASSURANCE ANALYST          | {:10.2f} | {:10.2f} | {:10.2f}".format(qa_analyst_cnt, 
    np.array(qa_analyst_slr).mean(), np.array(qa_analyst_slr).min(), np.array(qa_analyst_slr).max()))
print("{:4} QUALITY ASSURANCE ENGINEER         | {:10.2f} | {:10.2f} | {:10.2f}".format(qa_engineer_cnt, 
    np.array(qa_engineer_slr).mean(), np.array(qa_engineer_slr).min(), np.array(qa_engineer_slr).max()))
print("{:4} RESEARCH ENGINEER / SCIENTIST      | {:10.2f} | {:10.2f} | {:10.2f}".format(research_eng_cnt, 
    np.array(research_eng_slr).mean(), np.array(research_eng_slr).min(), np.array(research_eng_slr).max()))
print("{:4} SALES DEVELOPMENT REPR.            | {:10.2f} | {:10.2f} | {:10.2f}".format(sales_dev_repr_cnt, 
    np.array(sales_dev_repr_slr).mean(), np.array(sales_dev_repr_slr).min(), np.array(sales_dev_repr_slr).max()))
print("{:4} SALES ENGINEER                     | {:10.2f} | {:10.2f} | {:10.2f}".format(sales_eng_cnt, 
    np.array(sales_eng_slr).mean(), np.array(sales_eng_slr).min(), np.array(sales_eng_slr).max()))
print("{:4} SALESFORCE DEVELOPER               | {:10.2f} | {:10.2f} | {:10.2f}".format(salesforce_dev_cnt, 
    np.array(salesforce_dev_slr).mean(), np.array(salesforce_dev_slr).min(), np.array(salesforce_dev_slr).max()))
print("{:4} SECURITY ENGINEER                  | {:10.2f} | {:10.2f} | {:10.2f}".format(security_eng_cnt, 
    np.array(security_eng_slr).mean(), np.array(security_eng_slr).min(), np.array(security_eng_slr).max()))
print("{:4} SEO ANALYST / SPECIALIST           | {:10.2f} | {:10.2f} | {:10.2f}".format(seo_analyst_cnt, 
    np.array(seo_analyst_slr).mean(), np.array(seo_analyst_slr).min(), np.array(seo_analyst_slr).max()))
print("{:4} SERVICE MANAGEMENT                 | {:10.2f} | {:10.2f} | {:10.2f}".format(service_management_cnt, 
    np.array(service_management_slr).mean(), np.array(service_management_slr).min(), np.array(service_management_slr).max()))
print("{:4} SHAREPOINT DEVELOPER               | {:10.2f} | {:10.2f} | {:10.2f}".format(sharepoint_dev_cnt, 
    np.array(sharepoint_dev_slr).mean(), np.array(sharepoint_dev_slr).min(), np.array(sharepoint_dev_slr).max()))
print("{:4} SITE RELIABILITY ENGINEER          | {:10.2f} | {:10.2f} | {:10.2f}".format(site_reliability_eng_cnt, 
    np.array(site_reliability_eng_slr).mean(), np.array(site_reliability_eng_slr).min(), np.array(site_reliability_eng_slr).max()))
print("{:4} SOFTWARE QA ENGINEER               | {:10.2f} | {:10.2f} | {:10.2f}".format(software_qa_eng_cnt, 
    np.array(software_qa_eng_slr).mean(), np.array(software_qa_eng_slr).min(), np.array(software_qa_eng_slr).max()))
print("{:4} SOFTWARE ENGINEER                  | {:10.2f} | {:10.2f} | {:10.2f}".format(software_eng_cnt, 
    np.array(software_eng_slr).mean(), np.array(software_eng_slr).min(), np.array(software_eng_slr).max()))
print("{:4} SOFTWARE TEST ENGINEER             | {:10.2f} | {:10.2f} | {:10.2f}".format(software_test_eng_cnt, 
    np.array(software_test_eng_slr).mean(), np.array(software_test_eng_slr).min(), np.array(software_test_eng_slr).max()))
print("{:4} SOLUTIONS ENGINEER / ARCHITECT     | {:10.2f} | {:10.2f} | {:10.2f}".format(solutions_eng_cnt, 
    np.array(solutions_eng_slr).mean(), np.array(solutions_eng_slr).min(), np.array(solutions_eng_slr).max()))
print("{:4} STAFF ENGINEER                     | {:10.2f} | {:10.2f} | {:10.2f}".format(staff_eng_cnt, 
    np.array(staff_eng_slr).mean(), np.array(staff_eng_slr).min(), np.array(staff_eng_slr).max()))
print("{:4} SUPPLY CHAIN ANALYST               | {:10.2f} | {:10.2f} | {:10.2f}".format(supply_chain_analyst_cnt, 
    np.array(supply_chain_analyst_slr).mean(), np.array(supply_chain_analyst_slr).min(), np.array(supply_chain_analyst_slr).max()))
print("{:4} SUPPORT ENGINEER                   | {:10.2f} | {:10.2f} | {:10.2f}".format(support_eng_cnt, 
    np.array(support_eng_slr).mean(), np.array(support_eng_slr).min(), np.array(support_eng_slr).max()))
print("{:4} SYSTEM ADMINISTRATOR               | {:10.2f} | {:10.2f} | {:10.2f}".format(system_admin_cnt, 
    np.array(system_admin_slr).mean(), np.array(system_admin_slr).min(), np.array(system_admin_slr).max()))
print("{:4} SYSTEM ENGINEER                    | {:10.2f} | {:10.2f} | {:10.2f}".format(system_eng_cnt, 
    np.array(system_eng_slr).mean(), np.array(system_eng_slr).min(), np.array(system_eng_slr).max()))
print("{:4} TECHNICAL ENGINEER / ANALYST       | {:10.2f} | {:10.2f} | {:10.2f}".format(technical_eng_cnt, 
    np.array(technical_eng_slr).mean(), np.array(technical_eng_slr).min(), np.array(technical_eng_slr).max()))
print("{:4} UX / UI DESIGNER                   | {:10.2f} | {:10.2f} | {:10.2f}".format(ux_ui_designer_cnt, 
    np.array(ux_ui_designer_slr).mean(), np.array(ux_ui_designer_slr).min(), np.array(ux_ui_designer_slr).max()))
print("{:4} WEB DEVELOPER                      | {:10.2f} | {:10.2f} | {:10.2f}".format(web_developer_cnt, 
    np.array(web_developer_slr).mean(), np.array(web_developer_slr).min(), np.array(web_developer_slr).max()))
print("####### BLUE COLLAR POSITIONS ############### AVG ######## MIN ######## MAX ######")
print("{:4} ACCOUNT EXECUTIVE                  | {:10.2f} | {:10.2f} | {:10.2f}".format(account_executive_cnt, 
    np.array(account_executive_slr).mean(), np.array(account_executive_slr).min(), np.array(account_executive_slr).max()))
print("{:4} ACCOUNTANT                         | {:10.2f} | {:10.2f} | {:10.2f}".format(accountant_cnt, 
    np.array(accountant_slr).mean(), np.array(accountant_slr).min(), np.array(accountant_slr).max()))
print("{:4} ACTUARY                            | {:10.2f} | {:10.2f} | {:10.2f}".format(actuary_cnt, 
    np.array(actuary_slr).mean(), np.array(actuary_slr).min(), np.array(actuary_slr).max()))
print("{:4} ADMISSIONS COUNSELOR               | {:10.2f} | {:10.2f} | {:10.2f}".format(admissions_counselor_cnt, 
    np.array(admissions_counselor_slr).mean(), np.array(admissions_counselor_slr).min(), np.array(admissions_counselor_slr).max()))
print("{:4} AUDITOR                            | {:10.2f} | {:10.2f} | {:10.2f}".format(auditor_cnt, 
    np.array(auditor_slr).mean(), np.array(auditor_slr).min(), np.array(auditor_slr).max()))
print("{:4} BARISTA                            | {:10.2f} | {:10.2f} | {:10.2f}".format(barista_cnt, 
    np.array(barista_slr).mean(), np.array(barista_slr).min(), np.array(barista_slr).max()))
print("{:4} BARTENDER                          | {:10.2f} | {:10.2f} | {:10.2f}".format(bartender_cnt, 
    np.array(bartender_slr).mean(), np.array(bartender_slr).min(), np.array(bartender_slr).max()))
print("{:4} BEAUTY ADVISOR                     | {:10.2f} | {:10.2f} | {:10.2f}".format(beauty_advisor_cnt, 
    np.array(beauty_advisor_slr).mean(), np.array(beauty_advisor_slr).min(), np.array(beauty_advisor_slr).max()))
print("{:4} BOILERMAKER                        | {:10.2f} | {:10.2f} | {:10.2f}".format(boilermaker_cnt, 
    np.array(boilermaker_slr).mean(), np.array(boilermaker_slr).min(), np.array(boilermaker_slr).max()))
print("{:4} BOOKKEEPER                         | {:10.2f} | {:10.2f} | {:10.2f}".format(bookkeeper_cnt, 
    np.array(bookkeeper_slr).mean(), np.array(bookkeeper_slr).min(), np.array(bookkeeper_slr).max()))
print("{:4} CLAIMS ADJUSTER                    | {:10.2f} | {:10.2f} | {:10.2f}".format(claims_adjuster_cnt, 
    np.array(claims_adjuster_slr).mean(), np.array(claims_adjuster_slr).min(), np.array(claims_adjuster_slr).max()))
print("{:4} COMPLIANCE OFFICER                 | {:10.2f} | {:10.2f} | {:10.2f}".format(compliance_officer_cnt, 
    np.array(compliance_officer_slr).mean(), np.array(compliance_officer_slr).min(), np.array(compliance_officer_slr).max()))
print("{:4} CORPORATE COUNSEL                  | {:10.2f} | {:10.2f} | {:10.2f}".format(corporate_counsel_cnt, 
    np.array(corporate_counsel_slr).mean(), np.array(corporate_counsel_slr).min(), np.array(corporate_counsel_slr).max()))
print("{:4} CURRICULUM DEVELOPER               | {:10.2f} | {:10.2f} | {:10.2f}".format(curriculum_dev_cnt, 
    np.array(curriculum_dev_slr).mean(), np.array(curriculum_dev_slr).min(), np.array(curriculum_dev_slr).max()))
print("{:4} DELIVERY DRIVER                    | {:10.2f} | {:10.2f} | {:10.2f}".format(delivery_driver_cnt, 
    np.array(delivery_driver_slr).mean(), np.array(delivery_driver_slr).min(), np.array(delivery_driver_slr).max()))
print("{:4} DENTAL ASSISTANT                   | {:10.2f} | {:10.2f} | {:10.2f}".format(dental_assistant_cnt, 
    np.array(dental_assistant_slr).mean(), np.array(dental_assistant_slr).min(), np.array(dental_assistant_slr).max()))
print("{:4} ELECTRICIAN                        | {:10.2f} | {:10.2f} | {:10.2f}".format(electrician_cnt, 
    np.array(electrician_slr).mean(), np.array(electrician_slr).min(), np.array(electrician_slr).max()))
print("{:4} FOOD SCIENTIST                     | {:10.2f} | {:10.2f} | {:10.2f}".format(food_scientist_cnt, 
    np.array(food_scientist_slr).mean(), np.array(food_scientist_slr).min(), np.array(food_scientist_slr).max()))
print("{:4} INSIDE SALES                       | {:10.2f} | {:10.2f} | {:10.2f}".format(inside_sales_cnt, 
    np.array(inside_sales_slr).mean(), np.array(inside_sales_slr).min(), np.array(inside_sales_slr).max()))
print("{:4} INSURANCE AGENT                    | {:10.2f} | {:10.2f} | {:10.2f}".format(insurance_agent_cnt, 
    np.array(insurance_agent_slr).mean(), np.array(insurance_agent_slr).min(), np.array(insurance_agent_slr).max()))
print("{:4} LEGAL SECRETARY                    | {:10.2f} | {:10.2f} | {:10.2f}".format(legal_secretary_cnt, 
    np.array(legal_secretary_slr).mean(), np.array(legal_secretary_slr).min(), np.array(legal_secretary_slr).max()))
print("{:4} LIBRARIAN                          | {:10.2f} | {:10.2f} | {:10.2f}".format(librarian_cnt, 
    np.array(librarian_slr).mean(), np.array(librarian_slr).min(), np.array(librarian_slr).max()))
print("{:4} MEDICAL ASSISTANT                  | {:10.2f} | {:10.2f} | {:10.2f}".format(medical_assistant_cnt, 
    np.array(medical_assistant_slr).mean(), np.array(medical_assistant_slr).min(), np.array(medical_assistant_slr).max()))
print("{:4} MERCHANDISER                       | {:10.2f} | {:10.2f} | {:10.2f}".format(merchandiser_cnt, 
    np.array(merchandiser_slr).mean(), np.array(merchandiser_slr).min(), np.array(merchandiser_slr).max()))
print("{:4} NURSE                              | {:10.2f} | {:10.2f} | {:10.2f}".format(nurse_cnt, 
    np.array(nurse_slr).mean(), np.array(nurse_slr).min(), np.array(nurse_slr).max()))
print("{:4} OFFICE ADMINISTRATOR               | {:10.2f} | {:10.2f} | {:10.2f}".format(office_admin_cnt, 
    np.array(office_admin_slr).mean(), np.array(office_admin_slr).min(), np.array(office_admin_slr).max()))
print("{:4} OUTSIDE SALES                      | {:10.2f} | {:10.2f} | {:10.2f}".format(outside_sales_cnt, 
    np.array(outside_sales_slr).mean(), np.array(outside_sales_slr).min(), np.array(outside_sales_slr).max()))
print("{:4} PARALEGAL                          | {:10.2f} | {:10.2f} | {:10.2f}".format(paralegal_cnt, 
    np.array(paralegal_slr).mean(), np.array(paralegal_slr).min(), np.array(paralegal_slr).max()))
print("{:4} PARAMEDIC                          | {:10.2f} | {:10.2f} | {:10.2f}".format(paramedic_cnt, 
    np.array(paramedic_slr).mean(), np.array(paramedic_slr).min(), np.array(paramedic_slr).max()))
print("{:4} POLICE OFFICER                     | {:10.2f} | {:10.2f} | {:10.2f}".format(police_officer_cnt, 
    np.array(police_officer_slr).mean(), np.array(police_officer_slr).min(), np.array(police_officer_slr).max()))
print("{:4} PRINCIPAL                          | {:10.2f} | {:10.2f} | {:10.2f}".format(principal_cnt, 
    np.array(principal_slr).mean(), np.array(principal_slr).min(), np.array(principal_slr).max()))
print("{:4} PROGRAM COORDINATOR                | {:10.2f} | {:10.2f} | {:10.2f}".format(program_coord_cnt, 
    np.array(program_coord_slr).mean(), np.array(program_coord_slr).min(), np.array(program_coord_slr).max()))
print("{:4} REAL ESTATE AGENT                  | {:10.2f} | {:10.2f} | {:10.2f}".format(real_estate_agent_cnt, 
    np.array(real_estate_agent_slr).mean(), np.array(real_estate_agent_slr).min(), np.array(real_estate_agent_slr).max()))
print("{:4} RECRUIT                            | {:10.2f} | {:10.2f} | {:10.2f}".format(recruit_cnt, 
    np.array(recruit_slr).mean(), np.array(recruit_slr).min(), np.array(recruit_slr).max()))
print("{:4} RETAIL SALES                       | {:10.2f} | {:10.2f} | {:10.2f}".format(retail_sales_cnt, 
    np.array(retail_sales_slr).mean(), np.array(retail_sales_slr).min(), np.array(retail_sales_slr).max()))
print("{:4} SALES ASSOCIATE                    | {:10.2f} | {:10.2f} | {:10.2f}".format(sales_associate_cnt, 
    np.array(sales_associate_slr).mean(), np.array(sales_associate_slr).min(), np.array(sales_associate_slr).max()))
print("{:4} SCHOOL COUNSELOR                   | {:10.2f} | {:10.2f} | {:10.2f}".format(school_counselor_cnt, 
    np.array(school_counselor_slr).mean(), np.array(school_counselor_slr).min(), np.array(school_counselor_slr).max()))
print("{:4} SCHOOL PSYCHOLOGIST                | {:10.2f} | {:10.2f} | {:10.2f}".format(school_psychologist_cnt, 
    np.array(school_psychologist_slr).mean(), np.array(school_psychologist_slr).min(), np.array(school_psychologist_slr).max()))
print("{:4} SECURITY OFFICER                   | {:10.2f} | {:10.2f} | {:10.2f}".format(security_officer_cnt, 
    np.array(security_officer_slr).mean(), np.array(security_officer_slr).min(), np.array(security_officer_slr).max()))
print("{:4} SOCIAL WORKER                      | {:10.2f} | {:10.2f} | {:10.2f}".format(social_worker_cnt, 
    np.array(social_worker_slr).mean(), np.array(social_worker_slr).min(), np.array(social_worker_slr).max()))
print("{:4} SUPERVISOR                         | {:10.2f} | {:10.2f} | {:10.2f}".format(supervisor_cnt, 
    np.array(supervisor_slr).mean(), np.array(supervisor_slr).min(), np.array(supervisor_slr).max()))
print("{:4} TALENT ASSISTANT                   | {:10.2f} | {:10.2f} | {:10.2f}".format(talent_assistant_cnt, 
    np.array(talent_assistant_slr).mean(), np.array(talent_assistant_slr).min(), np.array(talent_assistant_slr).max()))
print("{:4} TAX ADVISOR                        | {:10.2f} | {:10.2f} | {:10.2f}".format(tax_advisor_cnt, 
    np.array(tax_advisor_slr).mean(), np.array(tax_advisor_slr).min(), np.array(tax_advisor_slr).max()))
print("{:4} TEACHER                            | {:10.2f} | {:10.2f} | {:10.2f}".format(teacher_cnt, 
    np.array(teacher_slr).mean(), np.array(teacher_slr).min(), np.array(teacher_slr).max()))
print("{:4} TECHNICIAN                         | {:10.2f} | {:10.2f} | {:10.2f}".format(technician_cnt, 
    np.array(technician_slr).mean(), np.array(technician_slr).min(), np.array(technician_slr).max()))
print("{:4} THERAPIST                          | {:10.2f} | {:10.2f} | {:10.2f}".format(therapist_cnt, 
    np.array(therapist_slr).mean(), np.array(therapist_slr).min(), np.array(therapist_slr).max()))
print("{:4} TOURING ASSISTANT                  | {:10.2f} | {:10.2f} | {:10.2f}".format(touring_assistant_cnt, 
    np.array(touring_assistant_slr).mean(), np.array(touring_assistant_slr).min(), np.array(touring_assistant_slr).max()))
print("{:4} TRANSPORTATION PLANNER             | {:10.2f} | {:10.2f} | {:10.2f}".format(transport_planner_cnt, 
    np.array(transport_planner_slr).mean(), np.array(transport_planner_slr).min(), np.array(transport_planner_slr).max()))
print("{:4} UNDERWRITER                        | {:10.2f} | {:10.2f} | {:10.2f}".format(underwriter_cnt, 
    np.array(underwriter_slr).mean(), np.array(underwriter_slr).min(), np.array(underwriter_slr).max()))
print("{:4} URBAN PLANNER                      | {:10.2f} | {:10.2f} | {:10.2f}".format(urban_planner_cnt, 
    np.array(urban_planner_slr).mean(), np.array(urban_planner_slr).min(), np.array(urban_planner_slr).max()))
print("{:4} VICE PRESIDENT                     | {:10.2f} | {:10.2f} | {:10.2f}".format(vice_president_cnt, 
    np.array(vice_president_slr).mean(), np.array(vice_president_slr).min(), np.array(vice_president_slr).max()))
print("{:4} WELDER                             | {:10.2f} | {:10.2f} | {:10.2f}".format(welder_cnt, 
    np.array(welder_slr).mean(), np.array(welder_slr).min(), np.array(welder_slr).max()))
print("####### OTHER NON-FITTING POSITIONS ######### AVG ######## MIN ######## MAX ######")
print("{:4} ANALYST                            | {:10.2f} | {:10.2f} | {:10.2f}".format(analyst_cnt, 
    np.array(analyst_slr).mean(), np.array(analyst_slr).min(), np.array(analyst_slr).max()))
print("{:4} DEVELOPER                          | {:10.2f} | {:10.2f} | {:10.2f}".format(developer_cnt, 
    np.array(developer_slr).mean(), np.array(developer_slr).min(), np.array(developer_slr).max()))
print("{:4} ENGINEER                           | {:10.2f} | {:10.2f} | {:10.2f}".format(engineer_cnt, 
    np.array(engineer_slr).mean(), np.array(engineer_slr).min(), np.array(engineer_slr).max()))
print("{:4} SERVER                             | {:10.2f} | {:10.2f} | {:10.2f}".format(server_cnt, 
    np.array(server_slr).mean(), np.array(server_slr).min(), np.array(server_slr).max()))
print("{:4} ASSISTANT                          | {:10.2f} | {:10.2f} | {:10.2f}".format(assistant_cnt, 
    np.array(assistant_slr).mean(), np.array(assistant_slr).min(), np.array(assistant_slr).max()))
print("############################################# AVG ######## MIN ######## MAX ######")
print("{:4} UNCATEGORIZED POSITIONS            | {:10.2f} | {:10.2f} | {:10.2f}".format(uncategorized_pos_cnt,
    np.array(uncategorized_pos_slr).mean(), np.array(uncategorized_pos_slr).min(), np.array(uncategorized_pos_slr).max()))
# for pos in uncategorized_pos[:40]:
#     print('>', pos)

####### WHITE COLLAR POSITIONS ############## AVG ######## MIN ######## MAX ######
  20 ACCOUNT MANAGER                    |  189300.00 |   46000.00 |  310000.00
  18 AI ENGINEER                        |  163745.61 |   49421.00 |  246000.00
 160 APPLICATION ENGINEER / DEVELOPER   |  191744.37 |   40925.00 |  278000.00
   6 AUTOMATION TESTER                  |  106726.33 |   70202.00 |  150000.00
  18 BACKEND DEVELOPER                  |  171555.56 |  105000.00 |  192000.00
 392 BUSINESS ANALYST                   |  121055.90 |   45390.00 |  265000.00
 167 BUSINESS INT. ENGINEER / DEVELOPER |  184679.16 |   70706.00 |  235000.00
  41 CHEMICAL ENGINEER                  |  111951.22 |   77000.00 |  182000.00
 215 CIVIL ENGINEER                     |  115093.02 |   75000.00 |  178000.00
  18 CLOUD ENGINEER                     |  127430.61 |   38397.00 |  220000.00
 187 CONSULTANT                         |  138935.54 |   45000.00 |  415000.00
  23 CONTENT DESIGNER                   |  133478.26 |   66000.00 |  226000.00
  26 CONTENT PRODUCER                   |  100269.23 |   65000.00 |  120000.00
 106 CONTENT STRATEGIST                 |  167547.17 |   73000.00 |  277000.00
  29 CUSTOMER ENGINEER                  |  262827.59 |   60000.00 |  438000.00
1067 DATA ANALYST                       |  128691.49 |   37719.00 |  388000.00
  21 DATA ARCHITECT                     |  211054.81 |   70340.00 |  275000.00
 156 DATA ENGINEER                      |  202045.95 |   43279.00 |  364000.00
1775 DATA SCIENTIST                     |  207121.88 |   61608.00 |  450000.00
  82 DATABASE ADMINISTRATOR             |  152829.27 |  100000.00 |  250000.00
  59 DATABASE ENGINEER                  |  221355.93 |  120000.00 |  360000.00
 114 DESIGN ENGINEER                    |  224210.53 |   77000.00 |  380000.00
 279 DEVOPS ENGINEER                    |  180631.11 |   49644.00 |  320000.00
  19 DISTINGUISED ENGINEER              |  304966.53 |  229364.00 |  368000.00
  12 E-COMMERCE                         |   85750.00 |   60000.00 |  122000.00
 195 ELECTRICAL ENGINEER                |  148579.49 |   67000.00 |  330000.00
  22 ENERGY ANALYST                     |   87409.09 |   60000.00 |  113000.00
  64 ENVIRONMENTAL ENGINEER             |  100812.50 |   65000.00 |  135000.00
 172 FINANCIAL ANALYST                  |  160738.37 |   77000.00 |  268000.00
 138 FRONTEND DEVELOPER                 |  215135.95 |   56706.00 |  360000.00
  30 FULLSTACK DEVELOPER                |  120790.87 |   43279.00 |  275000.00
  80 GRAPHIC DESIGNER                   |  108025.00 |   48000.00 |  210000.00
 174 HARDWARE ENGINEER                  |  343008.72 |  135000.00 |  540000.00
  33 HELP DESK SUPPORT TECHNICIAN       |   78000.00 |   61000.00 |  120000.00
   3 INFRASTRUCTURE ENGINEER            |  207661.00 |  120983.00 |  265000.00
  16 INVESTMENT BANKING ANALYST         |  170440.00 |   69152.00 |  250000.00
  27 IT ARCHITECT                       |  177333.33 |  144000.00 |  239000.00
  50 IT SUPPORT ENGINEER                |  103228.66 |   42237.00 |  250000.00
  12 JAVA DEVELOPER                     |  134666.67 |   94000.00 |  176000.00
 949 MACHINE LEARNING ENGINEER          |  216130.80 |   65656.00 |  425000.00
  34 MARKETING ANALYST                  |   84882.35 |   60000.00 |  121000.00
  66 MECHANICAL ENGINEER                |  193136.36 |   87000.00 |  300000.00
  12 MOBILE DEVELOPER                   |  159736.58 |   70010.00 |  232000.00
  27 NETWORK ADMINISTRATOR              |   88148.15 |   43000.00 |  123000.00
 398 NETWORK ENGINEER                   |  177825.31 |   49151.00 |  305000.00
  26 PETROLEUM ENGINEER                 |  194461.54 |  120000.00 |  228000.00
  12 PLATFORM ENGINEER                  |  102168.58 |   70010.00 |  171000.00
  32 POLICY ANALYST                     |   91281.25 |   55000.00 |  140000.00
  25 PROCESS ENGINEER                   |  158280.00 |   85000.00 |  211000.00
  32 PRODUCT DESIGNER / ENGINEER        |  174312.50 |  102000.00 |  303000.00
 347 PRODUCT MANAGER                    |  248948.52 |  105000.00 |  540000.00
 501 PROGRAM MANAGER                    |  231497.01 |   59000.00 |  480000.00
 303 PROJECT MANAGER                    |  163439.58 |   75349.00 |  330000.00
   4 PYTHON DEVELOPER                   |  180750.00 |  158000.00 |  231000.00
  12 QUALITY ASSURANCE ANALYST          |  134416.67 |   78000.00 |  200000.00
 110 QUALITY ASSURANCE ENGINEER         |  138995.35 |   43483.00 |  300000.00
  10 RESEARCH ENGINEER / SCIENTIST      |  210262.10 |   72955.00 |  383000.00
  85 SALES DEVELOPMENT REPR.            |   78905.88 |   40000.00 |  120000.00
 137 SALES ENGINEER                     |  161291.97 |  121000.00 |  316000.00
  10 SALESFORCE DEVELOPER               |  137600.00 |   93000.00 |  191000.00
 201 SECURITY ENGINEER                  |  264608.31 |   38397.00 |  390000.00
  16 SEO ANALYST / SPECIALIST           |   62625.00 |   39000.00 |   85000.00
   2 SERVICE MANAGEMENT                 |   99500.00 |   78000.00 |  121000.00
   7 SHAREPOINT DEVELOPER               |  127285.71 |   95000.00 |  160000.00
   4 SITE RELIABILITY ENGINEER          |   90938.50 |   63035.00 |  130000.00
 169 SOFTWARE QA ENGINEER               |  161471.56 |   47227.00 |  300000.00
4041 SOFTWARE ENGINEER                  |  175901.14 |   28158.00 |  560000.00
 274 SOFTWARE TEST ENGINEER             |  142979.66 |   47227.00 |  400000.00
  56 SOLUTIONS ENGINEER / ARCHITECT     |  139663.79 |   60487.00 |  300000.00
   8 STAFF ENGINEER                     |  219000.00 |  105000.00 |  362000.00
  88 SUPPLY CHAIN ANALYST               |  107920.45 |   68000.00 |  202000.00
 109 SUPPORT ENGINEER                   |  151399.33 |   42845.00 |  300000.00
  69 SYSTEM ADMINISTRATOR               |  137586.45 |   46465.00 |  260000.00
 122 SYSTEM ENGINEER                    |  169552.07 |   75000.00 |  390000.00
  29 TECHNICAL ENGINEER / ANALYST       |  145207.52 |   90000.00 |  213000.00
 461 UX / UI DESIGNER                   |  174587.85 |   83000.00 |  396000.00
  29 WEB DEVELOPER                      |  115655.17 |   50000.00 |  193000.00
####### BLUE COLLAR POSITIONS ############### AVG ######## MIN ######## MAX ######
 202 ACCOUNT EXECUTIVE                  |  144039.60 |   50000.00 |  345000.00
  60 ACCOUNTANT                         |  106550.00 |   73000.00 |  180000.00
 134 ACTUARY                            |  217395.52 |  112000.00 |  275000.00
  65 ADMISSIONS COUNSELOR               |   77430.77 |   47000.00 |  100000.00
  46 AUDITOR                            |   96521.74 |   65000.00 |  140000.00
  47 BARISTA                            |   41212.77 |   28000.00 |   55000.00
  30 BARTENDER                          |   93566.67 |   57000.00 |  133000.00
  43 BEAUTY ADVISOR                     |   45116.28 |   33000.00 |   60000.00
  12 BOILERMAKER                        |   80250.00 |   61000.00 |  100000.00
  18 BOOKKEEPER                         |   58833.33 |   26000.00 |  121000.00
  46 CLAIMS ADJUSTER                    |   91804.35 |   75000.00 |  118000.00
  58 COMPLIANCE OFFICER                 |  157620.69 |   82000.00 |  215000.00
 100 CORPORATE COUNSEL                  |  347990.00 |  137000.00 |  490000.00
  34 CURRICULUM DEVELOPER               |  128205.88 |   67000.00 |  220000.00
  26 DELIVERY DRIVER                    |   59423.08 |   45000.00 |   79000.00
  48 DENTAL ASSISTANT                   |   55458.33 |   45000.00 |   89000.00
  84 ELECTRICIAN                        |   97821.43 |   54000.00 |  130000.00
  18 FOOD SCIENTIST                     |   90777.78 |   73000.00 |  110000.00
  98 INSIDE SALES                       |   92255.10 |   45000.00 |  150000.00
  96 INSURANCE AGENT                    |   98802.08 |   43000.00 |  193000.00
  47 LEGAL SECRETARY                    |   94914.89 |   62000.00 |  125000.00
  54 LIBRARIAN                          |   89259.26 |   50000.00 |  120000.00
  97 MEDICAL ASSISTANT                  |   61907.22 |   35000.00 |  130000.00
  95 MERCHANDISER                       |   57094.74 |   35000.00 |   90000.00
 190 NURSE                              |  133431.58 |   40000.00 |  220000.00
   6 OFFICE ADMINISTRATOR               |   51833.33 |   39000.00 |   69000.00
 110 OUTSIDE SALES                      |  132545.45 |   60000.00 |  255000.00
  44 PARALEGAL                          |   74090.91 |   43000.00 |  110000.00
  22 PARAMEDIC                          |   71318.18 |   59000.00 |  104000.00
  50 POLICE OFFICER                     |  107260.00 |   62000.00 |  161000.00
  94 PRINCIPAL                          |  357648.44 |  140000.00 |  480000.00
  81 PROGRAM COORDINATOR                |   71098.77 |   49000.00 |   95000.00
 122 REAL ESTATE AGENT                  |  141942.62 |   68000.00 |  161000.00
   9 RECRUIT                            |  141777.78 |   87000.00 |  229000.00
   6 RETAIL SALES                       |   63833.33 |   35000.00 |   86000.00
  95 SALES ASSOCIATE                    |   58882.27 |   27000.00 |  145000.00
  81 SCHOOL COUNSELOR                   |   95123.46 |   58000.00 |  150000.00
 112 SCHOOL PSYCHOLOGIST                |  115625.00 |   70000.00 |  150000.00
  99 SECURITY OFFICER                   |   56323.23 |   28000.00 |   90000.00
 101 SOCIAL WORKER                      |   98811.88 |   60000.00 |  132000.00
  78 SUPERVISOR                         |   72589.74 |   41000.00 |  258000.00
   7 TALENT ASSISTANT                   |   53000.00 |   43000.00 |   80000.00
   5 TAX ADVISOR                        |   68800.00 |   48000.00 |  108000.00
  96 TEACHER                            |   92718.75 |   45000.00 |  125000.00
 207 TECHNICIAN                         |   68487.92 |   35000.00 |  490000.00
  48 THERAPIST                          |   94687.50 |   75000.00 |  150000.00
   5 TOURING ASSISTANT                  |   54200.00 |   47000.00 |   67000.00
  77 TRANSPORTATION PLANNER             |   93233.77 |   65000.00 |  140000.00
 107 UNDERWRITER                        |  109663.55 |   43000.00 |  166000.00
  13 URBAN PLANNER                      |   98461.54 |   70000.00 |  129000.00
  61 VICE PRESIDENT                     |  210377.39 |   91253.00 |  360000.00
  18 WELDER                             |   66333.33 |   50000.00 |   79000.00
####### OTHER NON-FITTING POSITIONS ######### AVG ######## MIN ######## MAX ######
  51 ANALYST                            |  103845.25 |   31973.00 |  242000.00
  38 DEVELOPER                          |  140403.79 |   41491.00 |  278000.00
  60 ENGINEER                           |  151273.55 |   43483.00 |  316000.00
  16 SERVER                             |  102062.50 |   77000.00 |  120000.00
  71 ASSISTANT                          |   64200.82 |   32000.00 |  282000.00
############################################# AVG ######## MIN ######## MAX ######
 973 UNCATEGORIZED POSITIONS            |  119520.34 |   21000.00 |  540000.00

## SALARY INFO BY POSITIONS (LIST INDEXES)

In [10]:
### Count each identified position of all rows, and collect their corresponding salaries
### Thankfully, there is neither null nor 'open-to-work' positions

### White collar positions in the list
white_collar_positions = ['Account Manager','AI Engineer','Application Engineer / Developer','Automation Tester','Backend Developer',
    'Business Analyst','Business Intelligence Eng. / Dev.','Chemical Engineer','Civil Engineer','Cloud Engineer','Consultant',
    'Content Designer','Content Producer','Content Strategist','Customer Engineer','Data Analyst','Data Architect','Data Engineer',
    'Data Scientist','Database Administrator','Database Engineer','Design Engineer','DevOps Engineer','Distinguished Engineer',
    'E-Commerce','Electrical Engineer','Energy Analyst','Environmental Engineer','Financial Analyst','Frontend Engineer',
    'Fullstack Developer','Graphic Designer','Hardware Engineer','Help Desk Support Technician','Infrastructure Engineer',
    'Investment Banking Analyst','IT Architect','IT Support Engineer','Java Developer','Machine Learning Engineer','Marketing Analyst',
    'Mechanical Engineer','Mobile Developer','Network Administrator','Network Engineer','Petroleum Engineer','Platform Engineer',
    'Policy Analyst','Process Engineer','Product Designer / Engineer','Product Manager','Program Manager','Project Manager',
    'Python Developer','Quality Assurance Analyst','Quality Assurance Engineer','Research Engineer / Scientist',
    'Sales Development Representative','Sales Engineer','Salesforce Developer','Security Engineer','SEO Analyst / Specialist',
    'Service Management','Sharepoint Developer','Site Reliability Engineer','Software QA Engineer','Software Engineer',
    'Software Test Engineer','Solutions Engineer / Architect','Staff Engineer','Supply Chain Analyst','Support Engineer',
    'System Administrator','System Engineer','Technical Engineer / Analyst','UX / UI Designer','Web Developer']
print(len(white_collar_positions), "WHITE COLLAR POSITIONS")
white_collar_positions_cnt = [0 for _ in range(len(white_collar_positions))]
white_collar_positions_slr = [[] for _ in range(len(white_collar_positions))]
# print(white_collar_positions_cnt)
# print(white_collar_positions_slr)
### Blue collar positions in the list
blue_collar_positions = ['Account Executive','Accountant','Actuary','Admissions Counselor','Auditor','Barista','Bartender',
    'Beauty Advisor','Boilermaker','Bookkeeper','Claims Adjuster','Compliance Officer','Corporate Counsel','Curriculum Developer',
    'Delivery Driver','Dental Assistant','Electrician','Food Scientist','Inside Sales','Insurance Agent','Legal Secretary',
    'Librarian','Medical Assistant','Merchandiser','Nurse','Office Administrator','Outside Sales','Paralegal','Paramedic','Police Officer',
    'Principal','Program Coordinator','Real Estate Agent','Recruit','Retail Sales','Sales Associate','School Counselor',
    'School Psychologist','Security Officer','Social Worker','Supervisor','Talent Assistant','Tax Advisor','Teacher','Technician',
    'Therapist','Touring Assistant','Transportation Planner','Underwriter','Urban Planner','Vice President','Welder']
print(len(blue_collar_positions), "BLUE COLLAR POSITIONS")
blue_collar_positions_cnt = [0 for _ in range(len(blue_collar_positions))]
blue_collar_positions_slr = [[] for _ in range(len(blue_collar_positions))]
# print(blue_collar_positions_cnt)
# print(blue_collar_positions_slr)
### Other positions in the list, that do not fit well in appropriate positions
other_positions = ['Analyst (Other)','Developer (Other)','Engineer (Other)','Server (Other)','Assistant (Other)']
print(len(other_positions), "OTHER POSITIONS")
other_positions_cnt = [0 for _ in range(len(other_positions))]
other_positions_slr = [[] for _ in range(len(other_positions))]
# print(other_positions_cnt)
# print(other_positions_slr)
# Uncategorized number of positions
position_uncategorized = 0;   position_uncategorized_salary = [];   position_uncategorized_examples = [];

77 WHITE COLLAR POSITIONS
52 BLUE COLLAR POSITIONS
5 OTHER POSITIONS

In [11]:
all_positions = salaries['position'].values
all_salaries = salaries['amount_usd'].values
for i in range(len(all_positions)):
    pos = all_positions[i];   salary = all_salaries[i];
    pos = pos.lower().replace('&','and')
    ### WHITE COLLAR POSITIONS ###
    if 'account manager' in pos:   
        white_collar_positions_cnt[0] += 1;   white_collar_positions_slr[0].append(salary);
    elif 'ai engineer' in pos or 'ai frameworks engineer' in pos:   
        white_collar_positions_cnt[1] += 1;   white_collar_positions_slr[1].append(salary); 
    elif 'application engineer' in pos or 'applications engineer' in pos or 'application developer' in pos:   
        white_collar_positions_cnt[2] += 1;   white_collar_positions_slr[2].append(salary);
    elif 'automation test' in pos:   
        white_collar_positions_cnt[3] += 1;   white_collar_positions_slr[3].append(salary); 
    elif 'backend developer' in pos or 'back end developer' in pos:   
        white_collar_positions_cnt[4] += 1;   white_collar_positions_slr[4].append(salary);
    elif 'business analyst' in pos or 'business intelligence analyst' in pos or 'business systems analyst' in pos \
      or 'business system analyst' in pos or 'business operations analyst' in pos or 'business tech analyst' in pos \
      or 'business technology analyst' in pos or 'business practice analyst' in pos or 'analyst.business' in pos \
      or 'business strategy analyst' in pos or 'business  analyst' in pos or 'business process analyst' in pos \
      or 'business management program analyst' in pos or 'business integrity analyst' in pos or 'analyst, business' in pos:
        white_collar_positions_cnt[5] += 1;   white_collar_positions_slr[5].append(salary);
    elif 'business intelligence engineer' in pos or 'bi engineer' in pos or 'business intelligence developer' in pos \
      or 'business intelligence lead engineer' in pos or 'business intelligence and analytics engineer' in pos \
      or 'bie' in pos:
        white_collar_positions_cnt[6] += 1;   white_collar_positions_slr[6].append(salary); 
    elif 'chemical engineer' in pos:   
        white_collar_positions_cnt[7] += 1;   white_collar_positions_slr[7].append(salary);
    elif 'civil engineer' in pos:   
        white_collar_positions_cnt[8] += 1;   white_collar_positions_slr[8].append(salary); 
    elif 'cloud engineer' in pos or 'cloud deployment engineer' in pos or 'cloud and innovation engineer' in pos:
        white_collar_positions_cnt[9] += 1;   white_collar_positions_slr[9].append(salary);
    elif 'consultant' in pos:   
        white_collar_positions_cnt[10] += 1;   white_collar_positions_slr[10].append(salary);
    elif 'content designer' in pos:   
        white_collar_positions_cnt[11] += 1;   white_collar_positions_slr[11].append(salary);
    elif 'content producer' in pos:   
        white_collar_positions_cnt[12] += 1;   white_collar_positions_slr[12].append(salary); 
    elif 'content strategist' in pos:   
        white_collar_positions_cnt[13] += 1;   white_collar_positions_slr[13].append(salary);
    elif 'customer engineer' in pos:   
        white_collar_positions_cnt[14] += 1;   white_collar_positions_slr[14].append(salary);
    elif 'data analyst' in pos or 'data analytics and reporting analyst' in pos or 'data systems analyst' in pos \
      or 'data science analyst' in pos or 'data intelligence analyst' in pos or 'data quality analyst' in pos \
      or 'data operations analyst' in pos or 'data governance analyst' in pos or 'data protection analyst' in pos \
      or 'data center analyst' in pos or 'data security analyst' in pos or 'data integrity analyst' in pos \
      or 'data and reporting analyst' in pos or 'data and compliance analyst' in pos or 'data insights analyst' in pos \
      or 'data reference analyst' in pos or 'analyst, data' in pos or 'analyst - data' in pos \
      or 'data quality and sales operations analyst' in pos or ('analyst' in pos and 'data' in pos):
        white_collar_positions_cnt[15] += 1;   white_collar_positions_slr[15].append(salary);
    elif 'data architect' in pos:   
        white_collar_positions_cnt[16] += 1;   white_collar_positions_slr[16].append(salary);
    elif 'data engineer' in pos:   
        white_collar_positions_cnt[17] += 1;   white_collar_positions_slr[17].append(salary);
    elif 'data scientist' in pos or 'data and applied scientist' in pos or 'applied scientist' in pos \
      or 'data and systems analyst' in pos or 'data science engineer' in pos or 'data science and engineering' in pos:
        white_collar_positions_cnt[18] += 1;   white_collar_positions_slr[18].append(salary);
    elif 'database administrator' in pos or 'database administration' in pos:   
        white_collar_positions_cnt[19] += 1;   white_collar_positions_slr[19].append(salary); 
    elif 'database engineer' in pos:   
        white_collar_positions_cnt[20] += 1;   white_collar_positions_slr[20].append(salary);
    elif 'design engineer' in pos or 'design verification engineer' in pos:   
        white_collar_positions_cnt[21] += 1;   white_collar_positions_slr[21].append(salary);
    elif 'devops engineer' in pos or 'devsecops' in pos or 'devops' in pos:   
        white_collar_positions_cnt[22] += 1;   white_collar_positions_slr[22].append(salary);
    elif 'distinguished engineer' in pos:   
        white_collar_positions_cnt[23] += 1;   white_collar_positions_slr[23].append(salary);
    elif 'ecommerce' in pos or 'e-commerce' in pos:   
        white_collar_positions_cnt[24] += 1;   white_collar_positions_slr[24].append(salary);
    elif 'electrical engineer' in pos:   
        white_collar_positions_cnt[25] += 1;   white_collar_positions_slr[25].append(salary);
    elif 'energy analyst' in pos or 'energy markets analyst' in pos:   
        white_collar_positions_cnt[26] += 1;   white_collar_positions_slr[26].append(salary);
    elif 'environmental engineer' in pos or 'environmental compliance engineer' in pos \
      or 'environmental consulting engineer' in pos:
        white_collar_positions_cnt[27] += 1;   white_collar_positions_slr[27].append(salary);
    elif 'financial analyst' in pos or 'finance operations analyst' in pos or 'finance project analyst' in pos \
      or 'finance analyst' in pos:   
        white_collar_positions_cnt[28] += 1;   white_collar_positions_slr[28].append(salary);
    elif 'frontend developer' in pos or 'front-end developer' in pos or 'front end developer' in pos \
      or 'frontend engineer' in pos or 'front-end engineer' in pos or 'front end engineer' in pos or 'react developer' in pos:
        white_collar_positions_cnt[29] += 1;   white_collar_positions_slr[29].append(salary);
    elif 'fullstack developer' in pos or 'full stack developer' in pos or 'full-stack developer' in pos \
      or 'fullstack engineer' in pos or 'full stack engineer' in pos or 'full-stack javascript developer' in pos \
      or 'full-stack react native developer' in pos:   
        white_collar_positions_cnt[30] += 1;   white_collar_positions_slr[30].append(salary);
    elif 'graphic designer' in pos:   
        white_collar_positions_cnt[31] += 1;   white_collar_positions_slr[31].append(salary);
    elif 'hardware engineer' in pos or 'hardware dev engineer' in pos or 'hardware development engineer' in pos:
        white_collar_positions_cnt[32] += 1;   white_collar_positions_slr[32].append(salary);
    elif 'help desk' in pos or 'helpdesk' in pos:   
        white_collar_positions_cnt[33] += 1;   white_collar_positions_slr[33].append(salary);
    elif 'infrastructure engineer' in pos:   
        white_collar_positions_cnt[34] += 1;   white_collar_positions_slr[34].append(salary);
    elif 'investment banking analyst' in pos:   
        white_collar_positions_cnt[35] += 1;   white_collar_positions_slr[35].append(salary);
    elif 'it architect' in pos or 'information technology architect' in pos:   
        white_collar_positions_cnt[36] += 1;   white_collar_positions_slr[36].append(salary);
    elif 'it support engineer' in pos or 'it engineer' in pos or 'information technology engineer' in pos \
      or 'information technology operations engineer' in pos or 'information architect' in pos:   
        white_collar_positions_cnt[37] += 1;   white_collar_positions_slr[37].append(salary);
    elif 'java developer' in pos or 'java/j2ee developer' in pos:   
        white_collar_positions_cnt[38] += 1;   white_collar_positions_slr[38].append(salary);
    elif 'machine learning engineer' in pos or 'machine learning scientist' in pos \
      or 'machine learning research engineer' in pos or 'machine learning and relevance engineer' in pos \
      or 'machine learning platform engineer' in pos or 'machine learning developer' in pos or 'deep learning/machine learning' in pos \
      or 'ml engineer' in pos or 'machine learning' in pos:   
        white_collar_positions_cnt[39] += 1;   white_collar_positions_slr[39].append(salary);
    elif 'marketing analyst' in pos or 'market analyst' in pos or 'market research and analysis' in pos \
      or 'market research manager' in pos or 'marketing operations analyst' in pos or 'market research analyst' in pos \
      or 'marketing execution analyst' in pos or 'marketing research analyst' in pos or 'marketing campaign analyst' in pos \
      or 'analyst, marketing' in pos:   
        white_collar_positions_cnt[40] += 1;   white_collar_positions_slr[40].append(salary);
    elif 'mechanical engineer' in pos:   
        white_collar_positions_cnt[41] += 1;   white_collar_positions_slr[41].append(salary);
    elif 'mobile developer' in pos or 'ios developer' in pos or 'ios engineer' in pos or 'ios/tvos engineer' in pos \
      or 'android developer' in pos or 'android engineer' in pos:
        white_collar_positions_cnt[42] += 1;   white_collar_positions_slr[42].append(salary);
    elif 'network administrator' in pos or 'network systems administrator' in pos:   
        white_collar_positions_cnt[43] += 1;   white_collar_positions_slr[43].append(salary);
    elif 'network engineer' in pos or 'network support engineer' in pos or 'network development engineer' in pos \
      or 'network consulting engineer' in pos:
        white_collar_positions_cnt[44] += 1;   white_collar_positions_slr[44].append(salary);
    elif 'petroleum engineer' in pos:   
        white_collar_positions_cnt[45] += 1;   white_collar_positions_slr[45].append(salary);
    elif 'platform engineer' in pos:   
        white_collar_positions_cnt[46] += 1;   white_collar_positions_slr[46].append(salary);
    elif 'policy analyst' in pos:   
        white_collar_positions_cnt[47] += 1;   white_collar_positions_slr[47].append(salary);
    elif 'process engineer' in pos:   
        white_collar_positions_cnt[48] += 1;   white_collar_positions_slr[48].append(salary);
    elif 'product designer' in pos or 'production engineer' in pos or 'product development engineer' in pos:
        white_collar_positions_cnt[49] += 1;   white_collar_positions_slr[49].append(salary);
    elif 'product manager' in pos or 'product engineering manager' in pos:   
        white_collar_positions_cnt[50] += 1;   white_collar_positions_slr[50].append(salary);
    elif 'program manager' in pos or 'program mgmt manager' in pos:   
        white_collar_positions_cnt[51] += 1;   white_collar_positions_slr[51].append(salary);
    elif 'project manager' in pos or 'project mananger' in pos:   
        white_collar_positions_cnt[52] += 1;   white_collar_positions_slr[52].append(salary);
    elif 'python developer' in pos:   
        white_collar_positions_cnt[53] += 1;   white_collar_positions_slr[53].append(salary);
    elif 'quality assurance analyst' in pos or 'qa analyst' in pos:   
        white_collar_positions_cnt[54] += 1;   white_collar_positions_slr[54].append(salary);
    elif 'quality assurance engineer' in pos or 'quality assurance specialist' in pos or 'quality engineer' in pos \
      or 'qa automation engineer' in pos or 'quality assurance automation engineer' in pos or 'qa tester engineer' in pos:
        white_collar_positions_cnt[55] += 1;   white_collar_positions_slr[55].append(salary);
    elif 'research engineer' in pos or 'research scientist' in pos:   
        white_collar_positions_cnt[56] += 1;   white_collar_positions_slr[56].append(salary);
    elif 'sales development representative' in pos:   
        white_collar_positions_cnt[57] += 1;   white_collar_positions_slr[57].append(salary);
    elif 'sales engineer' in pos:   
        white_collar_positions_cnt[58] += 1;   white_collar_positions_slr[58].append(salary);
    elif 'salesforce developer' in pos or 'salesforce admin and developer' in pos:   
        white_collar_positions_cnt[59] += 1;   white_collar_positions_slr[59].append(salary);
    elif 'security engineer' in pos:   
        white_collar_positions_cnt[60] += 1;   white_collar_positions_slr[60].append(salary);
    elif 'seo analyst' in pos or 'search engine optimization analyst' in pos or 'search engine optimization specialist' in pos:
        white_collar_positions_cnt[61] += 1;   white_collar_positions_slr[61].append(salary);
    elif 'service management' in pos:   
        white_collar_positions_cnt[62] += 1;   white_collar_positions_slr[62].append(salary);
    elif 'sharepoint developer' in pos:   
        white_collar_positions_cnt[63] += 1;   white_collar_positions_slr[63].append(salary);
    elif 'site reliability engineer' in pos:   
        white_collar_positions_cnt[64] += 1;   white_collar_positions_slr[64].append(salary);
    elif 'software qa engineer' in pos or 'qa engineer' in pos:   
        white_collar_positions_cnt[65] += 1;   white_collar_positions_slr[65].append(salary);
    elif 'software developer' in pos or 'software engineer' in pos or 'software development engineer' in pos \
      or 'software dev engineer' in pos or 'software analyst and developer' in pos or 'softwear developer' in pos \
      or 'engineer software' in pos or 'software firmware engineer' in pos or 'software  engineer' in pos \
      or 'software graphics engineer' in pos or 'firmware engineer' in pos or 'firmware development engineer' in pos \
      or 'software application development engineer' in pos or 'software build engineer' in pos \
      or 'software devlopment engineer' in pos:   
        white_collar_positions_cnt[66] += 1;   white_collar_positions_slr[66].append(salary);
    elif 'software test engineer' in pos or 'test engineer' in pos or 'test automation engineer' in pos \
      or 'test product development engineer' in pos or 'test technology engineer' in pos or 'test r and d engineer' in pos \
      or 'software test' in pos:
        white_collar_positions_cnt[67] += 1;   white_collar_positions_slr[67].append(salary);
    elif 'solutions engineer' in pos or 'solution engineer' in pos or 'solutions architect' in pos or 'solution architect' in pos:
        white_collar_positions_cnt[68] += 1;   white_collar_positions_slr[68].append(salary);
    elif 'staff engineer' in pos:   
        white_collar_positions_cnt[69] += 1;   white_collar_positions_slr[69].append(salary);
    elif 'supply chain analyst' in pos or 'supply chain solutions analyst' in pos or 'supply chain planning analyst' in pos \
      or 'supply chain associate analyst' in pos or 'supply chain program analyst' in pos or 'supply chain procurement analyst' in pos \
      or 'supply chain planning, mrp analyst' in pos:
        white_collar_positions_cnt[70] += 1;   white_collar_positions_slr[70].append(salary);
    elif 'support engineer' in pos or 'technical support engineer' in pos:   
        white_collar_positions_cnt[71] += 1;   white_collar_positions_slr[71].append(salary);
    elif 'system administrator' in pos:   
        white_collar_positions_cnt[72] += 1;   white_collar_positions_slr[72].append(salary);
    elif 'system engineer' in pos or 'systems engineer' in pos or 'systems admin/engineer' in pos \
      or 'system development engineer' in pos or 'system admin/engineer' in pos or 'systems development engineer' in pos:
        white_collar_positions_cnt[73] += 1;   white_collar_positions_slr[73].append(salary);
    elif 'technical engineer' in pos or 'technical analyst' in pos or 'technical solution analyst' in pos \
      or 'technical solutions analyst' in pos:
        white_collar_positions_cnt[74] += 1;   white_collar_positions_slr[74].append(salary);
    elif 'user experience designer' in pos or 'ux designer' in pos or 'interaction designer (ux)' in pos \
      or 'ux/ui designer' in pos or 'ux engineer' in pos or 'ui developer' in pos or 'user experience engineer' in pos \
      or 'ux researcher' in pos:
        white_collar_positions_cnt[75] += 1;   white_collar_positions_slr[75].append(salary);
    elif 'web developer' in pos or 'web production developer' in pos or 'website developer' in pos \
      or 'web solutions engineer' in pos or 'web apps' in pos:
        white_collar_positions_cnt[76] += 1;   white_collar_positions_slr[76].append(salary);
    ### BLUE COLLAR POSITIONS ###
    elif 'account executive' in pos:   
        blue_collar_positions_cnt[0] += 1;   blue_collar_positions_slr[0].append(salary);
    elif 'accountant' in pos:   
        blue_collar_positions_cnt[1] += 1;   blue_collar_positions_slr[1].append(salary);
    elif 'actuary' in pos:   
        blue_collar_positions_cnt[2] += 1;   blue_collar_positions_slr[2].append(salary);
    elif 'admission counselor' in pos or 'admissions counselor' in pos:   
        blue_collar_positions_cnt[3] += 1;   blue_collar_positions_slr[3].append(salary);
    elif 'auditor' in pos:   
        blue_collar_positions_cnt[4] += 1;   blue_collar_positions_slr[4].append(salary);
    elif 'barista' in pos:   
        blue_collar_positions_cnt[5] += 1;   blue_collar_positions_slr[5].append(salary);
    elif 'bartender' in pos:   
        blue_collar_positions_cnt[6] += 1;   blue_collar_positions_slr[6].append(salary);
    elif 'beauty advisor' in pos:   
        blue_collar_positions_cnt[7] += 1;   blue_collar_positions_slr[7].append(salary);
    elif 'boilermaker' in pos:   
        blue_collar_positions_cnt[8] += 1;   blue_collar_positions_slr[8].append(salary);
    elif 'bookkeeper' in pos:   
        blue_collar_positions_cnt[9] += 1;   blue_collar_positions_slr[9].append(salary);
    elif 'claims adjuster' in pos:   
        blue_collar_positions_cnt[10] += 1;   blue_collar_positions_slr[10].append(salary);
    elif 'compliance officer' in pos or 'compliance business control officer' in pos:   
        blue_collar_positions_cnt[11] += 1;   blue_collar_positions_slr[11].append(salary);
    elif 'corporate counsel' in pos:   
        blue_collar_positions_cnt[12] += 1;   blue_collar_positions_slr[12].append(salary);
    elif 'curriculum developer' in pos:   
        blue_collar_positions_cnt[13] += 1;   blue_collar_positions_slr[13].append(salary);
    elif 'delivery driver' in pos:   
        blue_collar_positions_cnt[14] += 1;   blue_collar_positions_slr[14].append(salary);
    elif 'dental assistant' in pos:   
        blue_collar_positions_cnt[15] += 1;   blue_collar_positions_slr[15].append(salary);
    elif 'electrician' in pos:   
        blue_collar_positions_cnt[16] += 1;   blue_collar_positions_slr[16].append(salary);
    elif 'food scientist' in pos:   
        blue_collar_positions_cnt[17] += 1;   blue_collar_positions_slr[17].append(salary);
    elif 'inside sales' in pos:   
        blue_collar_positions_cnt[18] += 1;   blue_collar_positions_slr[18].append(salary);
    elif 'insurance agent' in pos:   
        blue_collar_positions_cnt[19] += 1;   blue_collar_positions_slr[19].append(salary);
    elif 'legal secretary' in pos:   
        blue_collar_positions_cnt[20] += 1;   blue_collar_positions_slr[20].append(salary);
    elif 'librarian' in pos:   
        blue_collar_positions_cnt[21] += 1;   blue_collar_positions_slr[21].append(salary);
    elif 'medical assistant' in pos:   
        blue_collar_positions_cnt[22] += 1;   blue_collar_positions_slr[22].append(salary);
    elif 'merchandiser' in pos:   
        blue_collar_positions_cnt[23] += 1;   blue_collar_positions_slr[23].append(salary);
    elif 'nurse' in pos:   
        blue_collar_positions_cnt[24] += 1;   blue_collar_positions_slr[24].append(salary);
    elif 'office administrator' in pos:   
        blue_collar_positions_cnt[25] += 1;   blue_collar_positions_slr[25].append(salary);
    elif 'outside sales' in pos:   
        blue_collar_positions_cnt[26] += 1;   blue_collar_positions_slr[26].append(salary);
    elif 'paralegal' in pos:   
        blue_collar_positions_cnt[27] += 1;   blue_collar_positions_slr[27].append(salary);
    elif 'paramedic' in pos:   
        blue_collar_positions_cnt[28] += 1;   blue_collar_positions_slr[28].append(salary);
    elif 'police officer' in pos:   
        blue_collar_positions_cnt[29] += 1;   blue_collar_positions_slr[29].append(salary);
    elif 'principal' in pos:   
        blue_collar_positions_cnt[30] += 1;   blue_collar_positions_slr[30].append(salary);
    elif 'program coordinator' in pos:   
        blue_collar_positions_cnt[31] += 1;   blue_collar_positions_slr[31].append(salary);  
    elif 'real estate agent' in pos:   
        blue_collar_positions_cnt[32] += 1;   blue_collar_positions_slr[32].append(salary);
    elif 'recruit' in pos:   
        blue_collar_positions_cnt[33] += 1;   blue_collar_positions_slr[33].append(salary);
    elif 'retail sales' in pos:   
        blue_collar_positions_cnt[34] += 1;   blue_collar_positions_slr[34].append(salary);
    elif 'sales associate' in pos:   
        blue_collar_positions_cnt[35] += 1;   blue_collar_positions_slr[35].append(salary);
    elif 'school counselor' in pos:   
        blue_collar_positions_cnt[36] += 1;   blue_collar_positions_slr[36].append(salary);
    elif 'school psychologist' in pos:   
        blue_collar_positions_cnt[37] += 1;   blue_collar_positions_slr[37].append(salary);
    elif 'security officer' in pos or 'security guard' in pos:   
        blue_collar_positions_cnt[38] += 1;   blue_collar_positions_slr[38].append(salary);
    elif 'social worker' in pos:   
        blue_collar_positions_cnt[39] += 1;   blue_collar_positions_slr[39].append(salary);
    elif 'supervisor' in pos:   
        blue_collar_positions_cnt[40] += 1;   blue_collar_positions_slr[40].append(salary);
    elif 'talent assistant' in pos or 'assistant, talent' in pos:   
        blue_collar_positions_cnt[41] += 1;   blue_collar_positions_slr[41].append(salary);
    elif 'tax advisor' in pos:   
        blue_collar_positions_cnt[42] += 1;   blue_collar_positions_slr[42].append(salary); 
    elif 'teacher' in pos:   
        blue_collar_positions_cnt[43] += 1;   blue_collar_positions_slr[43].append(salary);
    elif 'technician' in pos:   
        blue_collar_positions_cnt[44] += 1;   blue_collar_positions_slr[44].append(salary);
    elif 'therapist' in pos:   
        blue_collar_positions_cnt[45] += 1;   blue_collar_positions_slr[45].append(salary);
    elif 'touring assistant' in pos or ('touring' in pos and 'assistant' in pos):   
        blue_collar_positions_cnt[46] += 1;   blue_collar_positions_slr[46].append(salary);
    elif 'transportation planner' in pos:   
        blue_collar_positions_cnt[47] += 1;   blue_collar_positions_slr[47].append(salary);
    elif 'underwriter' in pos:   
        blue_collar_positions_cnt[48] += 1;   blue_collar_positions_slr[48].append(salary);
    elif 'urban planner' in pos:   
        blue_collar_positions_cnt[49] += 1;   blue_collar_positions_slr[49].append(salary);
    elif 'vice president' in pos:   
        blue_collar_positions_cnt[50] += 1;   blue_collar_positions_slr[50].append(salary);
    elif 'welder' in pos:   
        blue_collar_positions_cnt[51] += 1;   blue_collar_positions_slr[51].append(salary);
    ### Other non-fitting positions ###
    elif 'analyst' in pos:     other_positions_cnt[0] += 1;    other_positions_slr[0].append(salary);
    elif 'developer' in pos:   other_positions_cnt[1] += 1;    other_positions_slr[1].append(salary);
    elif 'engineer' in pos:    other_positions_cnt[2] += 1;    other_positions_slr[2].append(salary);
    elif 'server' in pos:      other_positions_cnt[3] += 1;    other_positions_slr[3].append(salary);
    elif 'assistant' in pos:   other_positions_cnt[4] += 1;    other_positions_slr[4].append(salary);
    else:   position_uncategorized += 1;  position_uncategorized_salary.append(salary);    position_uncategorized_examples.append(pos);

In [12]:
print("#### COUNTS OF ALL WHITE COLLAR POSITIONS ####")
print(white_collar_positions_cnt, '-->', sum(white_collar_positions_cnt))
print("#### COUNTS OF ALL BLUE COLLAR POSITIONS ####")
print(blue_collar_positions_cnt, '-->', sum(blue_collar_positions_cnt))
print("#### COUNTS OF ALL OTHER POSITIONS ####")
print(other_positions_cnt, '-->', sum(other_positions_cnt))
print("#### {} UNCATEGORIZED POSITIONS ####".format(position_uncategorized))

#### COUNTS OF ALL WHITE COLLAR POSITIONS ####
[20, 18, 160, 6, 18, 392, 167, 41, 215, 18, 187, 23, 26, 106, 29, 1067, 21, 156, 1775, 82, 59, 114, 279, 19, 12, 195, 22, 64, 172, 138, 30, 80, 174, 33, 3, 16, 27, 50, 12, 949, 34, 66, 12, 27, 398, 26, 12, 32, 25, 32, 347, 501, 303, 4, 12, 110, 10, 85, 137, 10, 201, 16, 2, 7, 4, 169, 4041, 274, 56, 8, 88, 109, 69, 122, 29, 461, 29] --> 14843
#### COUNTS OF ALL BLUE COLLAR POSITIONS ####
[202, 60, 134, 65, 46, 47, 30, 43, 12, 18, 46, 58, 100, 34, 26, 48, 84, 18, 98, 96, 47, 54, 97, 95, 190, 6, 110, 44, 22, 50, 94, 81, 122, 9, 6, 95, 81, 112, 99, 101, 78, 7, 5, 96, 207, 48, 5, 77, 107, 13, 61, 18] --> 3502
#### COUNTS OF ALL OTHER POSITIONS ####
[51, 38, 60, 16, 71] --> 236
#### 973 UNCATEGORIZED POSITIONS ####

In [13]:
print("############################ COUNT ##### AVG ######## STD ######## MIN ######## 25% ######## 50% ######## 75% ######## MAX ####")
print("UNCATEGORIZED POSITIONS     | {:4} | {:10.2f} | {:10.2f} | {:10.2f} | {:10.2f} | {:10.2f} | {:10.2f} | {:10.2f}".format(
    position_uncategorized, np.array(position_uncategorized_salary).mean(), np.array(position_uncategorized_salary).std(), 
    np.array(position_uncategorized_salary).min(), np.percentile(position_uncategorized_salary, 25), 
    np.percentile(position_uncategorized_salary, 50), np.percentile(position_uncategorized_salary, 75),
    np.array(position_uncategorized_salary).max()))

############################ COUNT ##### AVG ######## STD ######## MIN ######## 25% ######## 50% ######## 75% ######## MAX ####
UNCATEGORIZED POSITIONS     |  973 |  119520.34 |   71848.93 |   21000.00 |   69000.00 |  100928.00 |  150000.00 |  540000.00

In [14]:
print("#### WHITE COLLAR POSITION ######### COUNT ##### AVG ######## STD ######## MIN ######## 25% ######## 50% ######## 75% ######## MAX ####")
for i in range(len(white_collar_positions)):
    print("{:35} | {:4} | {:10.2f} | {:10.2f} | {:10.2f} | {:10.2f} | {:10.2f} | {:10.2f} | {:10.2f}".format(
        white_collar_positions[i].upper(), white_collar_positions_cnt[i], np.array(white_collar_positions_slr[i]).mean(),
        np.array(white_collar_positions_slr[i]).std(), np.array(white_collar_positions_slr[i]).min(), 
        np.percentile(white_collar_positions_slr[i], 25), np.percentile(white_collar_positions_slr[i], 50), 
        np.percentile(white_collar_positions_slr[i], 75), np.array(white_collar_positions_slr[i]).max()))

#### WHITE COLLAR POSITION ######### COUNT ##### AVG ######## STD ######## MIN ######## 25% ######## 50% ######## 75% ######## MAX ####
ACCOUNT MANAGER                     |   20 |  189300.00 |   82284.93 |   46000.00 |  130000.00 |  180000.00 |  258250.00 |  310000.00
AI ENGINEER                         |   18 |  163745.61 |   45271.52 |   49421.00 |  151250.00 |  163000.00 |  192000.00 |  246000.00
APPLICATION ENGINEER / DEVELOPER    |  160 |  191744.37 |   41621.55 |   40925.00 |  168500.00 |  195000.00 |  213750.00 |  278000.00
AUTOMATION TESTER                   |    6 |  106726.33 |   27735.72 |   70202.00 |   84867.00 |  105500.00 |  124750.00 |  150000.00
BACKEND DEVELOPER                   |   18 |  171555.56 |   21443.01 |  105000.00 |  172000.00 |  173500.00 |  184750.00 |  192000.00
BUSINESS ANALYST                    |  392 |  121055.90 |   44875.96 |   45390.00 |   90000.00 |  113500.00 |  150000.00 |  265000.00
BUSINESS INTELLIGENCE ENG. / DEV.   |  167 |  184679.16 |   28089.28 |   70706.00 |  174000.00 |  185000.00 |  205000.00 |  235000.00
CHEMICAL ENGINEER                   |   41 |  111951.22 |   28181.43 |   77000.00 |   88000.00 |  107000.00 |  135000.00 |  182000.00
CIVIL ENGINEER                      |  215 |  115093.02 |   25560.70 |   75000.00 |   95000.00 |  110000.00 |  134000.00 |  178000.00
CLOUD ENGINEER                      |   18 |  127430.61 |   55670.82 |   38397.00 |   88926.25 |  106984.50 |  177750.00 |  220000.00
CONSULTANT                          |  187 |  138935.54 |   78075.81 |   45000.00 |   71000.00 |  118000.00 |  181500.00 |  415000.00
CONTENT DESIGNER                    |   23 |  133478.26 |   42301.06 |   66000.00 |  110500.00 |  119000.00 |  165500.00 |  226000.00
CONTENT PRODUCER                    |   26 |  100269.23 |   15300.97 |   65000.00 |   90000.00 |   98500.00 |  116000.00 |  120000.00
CONTENT STRATEGIST                  |  106 |  167547.17 |   49116.94 |   73000.00 |  135000.00 |  174000.00 |  198750.00 |  277000.00
CUSTOMER ENGINEER                   |   29 |  262827.59 |   91549.15 |   60000.00 |  230000.00 |  268000.00 |  316000.00 |  438000.00
DATA ANALYST                        | 1067 |  128691.49 |   36881.66 |   37719.00 |  102000.00 |  123000.00 |  149000.00 |  388000.00
DATA ARCHITECT                      |   21 |  211054.81 |   49175.60 |   70340.00 |  210000.00 |  224000.00 |  234000.00 |  275000.00
DATA ENGINEER                       |  156 |  202045.95 |   72004.13 |   43279.00 |  163500.00 |  188500.00 |  240000.00 |  364000.00
DATA SCIENTIST                      | 1775 |  207121.88 |   63409.62 |   61608.00 |  157500.00 |  197000.00 |  255000.00 |  450000.00
DATABASE ADMINISTRATOR              |   82 |  152829.27 |   28657.27 |  100000.00 |  131250.00 |  150000.00 |  170000.00 |  250000.00
DATABASE ENGINEER                   |   59 |  221355.93 |   64464.09 |  120000.00 |  168000.00 |  200000.00 |  260000.00 |  360000.00
DESIGN ENGINEER                     |  114 |  224210.53 |   64174.03 |   77000.00 |  186500.00 |  223000.00 |  269000.00 |  380000.00
DEVOPS ENGINEER                     |  279 |  180631.11 |   50233.75 |   49644.00 |  150000.00 |  170000.00 |  200000.00 |  320000.00
DISTINGUISHED ENGINEER              |   19 |  304966.53 |   41434.66 |  229364.00 |  292000.00 |  300000.00 |  348000.00 |  368000.00
E-COMMERCE                          |   12 |   85750.00 |   17488.69 |   60000.00 |   71750.00 |   95000.00 |   95000.00 |  122000.00
ELECTRICAL ENGINEER                 |  195 |  148579.49 |   70529.34 |   67000.00 |   98000.00 |  120000.00 |  157500.00 |  330000.00
ENERGY ANALYST                      |   22 |   87409.09 |   16052.92 |   60000.00 |   77000.00 |   80000.00 |  104500.00 |  113000.00
ENVIRONMENTAL ENGINEER              |   64 |  100812.50 |   19966.28 |   65000.00 |   85000.00 |   98000.00 |  116000.00 |  135000.00
FINANCIAL ANALYST                   |  172 |  160738.37 |   45900.63 |   77000.00 |  129750.00 |  150500.00 |  200000.00 |  268000.00
FRONTEND ENGINEER                   |  138 |  215135.95 |   81243.74 |   56706.00 |  150000.00 |  224500.00 |  273000.00 |  360000.00
FULLSTACK DEVELOPER                 |   30 |  120790.87 |   54607.70 |   43279.00 |   76318.75 |  108000.00 |  159250.00 |  275000.00
GRAPHIC DESIGNER                    |   80 |  108025.00 |   33237.02 |   48000.00 |   88000.00 |  103000.00 |  123250.00 |  210000.00
HARDWARE ENGINEER                   |  174 |  343008.72 |  127298.03 |  135000.00 |  245000.00 |  341000.00 |  450000.00 |  540000.00
HELP DESK SUPPORT TECHNICIAN        |   33 |   78000.00 |   14238.23 |   61000.00 |   68000.00 |   73000.00 |   85000.00 |  120000.00
INFRASTRUCTURE ENGINEER             |    3 |  207661.00 |   62347.45 |  120983.00 |  178991.50 |  237000.00 |  251000.00 |  265000.00
INVESTMENT BANKING ANALYST          |   16 |  170440.00 |   62782.93 |   69152.00 |  126931.25 |  172500.00 |  231250.00 |  250000.00
IT ARCHITECT                        |   27 |  177333.33 |   19537.24 |  144000.00 |  161000.00 |  180000.00 |  190000.00 |  239000.00
IT SUPPORT ENGINEER                 |   50 |  103228.66 |   36768.24 |   42237.00 |   84000.00 |   95500.00 |  109250.00 |  250000.00
JAVA DEVELOPER                      |   12 |  134666.67 |   27902.61 |   94000.00 |  116250.00 |  128000.00 |  163250.00 |  176000.00
MACHINE LEARNING ENGINEER           |  949 |  216130.80 |   60598.31 |   65656.00 |  169000.00 |  210000.00 |  258000.00 |  425000.00
MARKETING ANALYST                   |   34 |   84882.35 |   15620.06 |   60000.00 |   74250.00 |   80000.00 |   96000.00 |  121000.00
MECHANICAL ENGINEER                 |   66 |  193136.36 |   60642.99 |   87000.00 |  135000.00 |  194500.00 |  249250.00 |  300000.00
MOBILE DEVELOPER                    |   12 |  159736.58 |   53705.84 |   70010.00 |  123750.00 |  162000.00 |  195000.00 |  232000.00
NETWORK ADMINISTRATOR               |   27 |   88148.15 |   21624.24 |   43000.00 |   70000.00 |   90000.00 |  107000.00 |  123000.00
NETWORK ENGINEER                    |  398 |  177825.31 |   55403.08 |   49151.00 |  138000.00 |  165000.00 |  216500.00 |  305000.00
PETROLEUM ENGINEER                  |   26 |  194461.54 |   33783.51 |  120000.00 |  172500.00 |  198500.00 |  226000.00 |  228000.00
PLATFORM ENGINEER                   |   12 |  102168.58 |   31053.22 |   70010.00 |   75308.00 |   98283.00 |  109555.50 |  171000.00
POLICY ANALYST                      |   32 |   91281.25 |   20270.41 |   55000.00 |   75000.00 |   88500.00 |  109000.00 |  140000.00
PROCESS ENGINEER                    |   25 |  158280.00 |   27632.62 |   85000.00 |  139000.00 |  157000.00 |  185000.00 |  211000.00
PRODUCT DESIGNER / ENGINEER         |   32 |  174312.50 |   45603.89 |  102000.00 |  142000.00 |  166500.00 |  197500.00 |  303000.00
PRODUCT MANAGER                     |  347 |  248948.52 |   73678.60 |  105000.00 |  197500.00 |  235000.00 |  300000.00 |  540000.00
PROGRAM MANAGER                     |  501 |  231497.01 |   81488.22 |   59000.00 |  176000.00 |  210000.00 |  265000.00 |  480000.00
PROJECT MANAGER                     |  303 |  163439.58 |   42130.50 |   75349.00 |  131000.00 |  160000.00 |  190000.00 |  330000.00
PYTHON DEVELOPER                    |    4 |  180750.00 |   29252.14 |  158000.00 |  164000.00 |  167000.00 |  183750.00 |  231000.00
QUALITY ASSURANCE ANALYST           |   12 |  134416.67 |   38571.27 |   78000.00 |  105250.00 |  134000.00 |  151250.00 |  200000.00
QUALITY ASSURANCE ENGINEER          |  110 |  138995.35 |   63089.01 |   43483.00 |   98250.00 |  143000.00 |  180000.00 |  300000.00
RESEARCH ENGINEER / SCIENTIST       |   10 |  210262.10 |  106624.62 |   72955.00 |  126000.00 |  176333.00 |  302500.00 |  383000.00
SALES DEVELOPMENT REPRESENTATIVE    |   85 |   78905.88 |   14732.62 |   40000.00 |   70000.00 |   80000.00 |   86000.00 |  120000.00
SALES ENGINEER                      |  137 |  161291.97 |   45074.17 |  121000.00 |  132000.00 |  145000.00 |  170000.00 |  316000.00
SALESFORCE DEVELOPER                |   10 |  137600.00 |   32836.56 |   93000.00 |  110250.00 |  146000.00 |  153750.00 |  191000.00
SECURITY ENGINEER                   |  201 |  264608.31 |   76463.41 |   38397.00 |  201000.00 |  280000.00 |  303000.00 |  390000.00
SEO ANALYST / SPECIALIST            |   16 |   62625.00 |   13359.80 |   39000.00 |   49250.00 |   64000.00 |   74000.00 |   85000.00
SERVICE MANAGEMENT                  |    2 |   99500.00 |   21500.00 |   78000.00 |   88750.00 |   99500.00 |  110250.00 |  121000.00
SHAREPOINT DEVELOPER                |    7 |  127285.71 |   20892.34 |   95000.00 |  113500.00 |  135000.00 |  137000.00 |  160000.00
SITE RELIABILITY ENGINEER           |    4 |   90938.50 |   25729.59 |   63035.00 |   70882.25 |   85359.50 |  105415.75 |  130000.00
SOFTWARE QA ENGINEER                |  169 |  161471.56 |   51479.18 |   47227.00 |  130000.00 |  153000.00 |  195000.00 |  300000.00
SOFTWARE ENGINEER                   | 4041 |  175901.14 |   81281.69 |   28158.00 |  113463.00 |  161000.00 |  230000.00 |  560000.00
SOFTWARE TEST ENGINEER              |  274 |  142979.66 |   54508.46 |   47227.00 |  108176.75 |  136000.00 |  170000.00 |  400000.00
SOLUTIONS ENGINEER / ARCHITECT      |   56 |  139663.79 |   56724.37 |   60487.00 |  100811.00 |  116597.00 |  166000.00 |  300000.00
STAFF ENGINEER                      |    8 |  219000.00 |   91185.25 |  105000.00 |  141750.00 |  199000.00 |  295000.00 |  362000.00
SUPPLY CHAIN ANALYST                |   88 |  107920.45 |   25773.59 |   68000.00 |   90000.00 |  100000.00 |  120500.00 |  202000.00
SUPPORT ENGINEER                    |  109 |  151399.33 |   52951.89 |   42845.00 |  116000.00 |  150000.00 |  180000.00 |  300000.00
SYSTEM ADMINISTRATOR                |   69 |  137586.45 |   40426.33 |   46465.00 |  107000.00 |  130000.00 |  158000.00 |  260000.00
SYSTEM ENGINEER                     |  122 |  169552.07 |   61700.80 |   75000.00 |  130000.00 |  160000.00 |  210000.00 |  390000.00
TECHNICAL ENGINEER / ANALYST        |   29 |  145207.52 |   28766.20 |   90000.00 |  125000.00 |  144000.00 |  155000.00 |  213000.00
UX / UI DESIGNER                    |  461 |  174587.85 |   55280.47 |   83000.00 |  132000.00 |  166000.00 |  210000.00 |  396000.00
WEB DEVELOPER                       |   29 |  115655.17 |   32510.24 |   50000.00 |   96000.00 |   96000.00 |  145000.00 |  193000.00

In [15]:
print("#### BLUE COLLAR POSITION ########## COUNT ##### AVG ######## STD ######## MIN ######## 25% ######## 50% ######## 75% ######## MAX ####")
for i in range(len(blue_collar_positions)):
    print("{:35} | {:4} | {:10.2f} | {:10.2f} | {:10.2f} | {:10.2f} | {:10.2f} | {:10.2f} | {:10.2f}".format(
        blue_collar_positions[i].upper(), blue_collar_positions_cnt[i], np.array(blue_collar_positions_slr[i]).mean(),
        np.array(blue_collar_positions_slr[i]).std(), np.array(blue_collar_positions_slr[i]).min(),  
        np.percentile(blue_collar_positions_slr[i], 25), np.percentile(blue_collar_positions_slr[i], 50), 
        np.percentile(blue_collar_positions_slr[i], 75), np.array(blue_collar_positions_slr[i]).max()))

#### BLUE COLLAR POSITION ########## COUNT ##### AVG ######## STD ######## MIN ######## 25% ######## 50% ######## 75% ######## MAX ####
ACCOUNT EXECUTIVE                   |  202 |  144039.60 |   75633.03 |   50000.00 |   90000.00 |  110000.00 |  179000.00 |  345000.00
ACCOUNTANT                          |   60 |  106550.00 |   22097.08 |   73000.00 |   90000.00 |  109000.00 |  110000.00 |  180000.00
ACTUARY                             |  134 |  217395.52 |   37727.62 |  112000.00 |  191500.00 |  220000.00 |  250000.00 |  275000.00
ADMISSIONS COUNSELOR                |   65 |   77430.77 |   12547.72 |   47000.00 |   70000.00 |   78000.00 |   86000.00 |  100000.00
AUDITOR                             |   46 |   96521.74 |   19310.66 |   65000.00 |   80000.00 |  100000.00 |  110000.00 |  140000.00
BARISTA                             |   47 |   41212.77 |    6490.37 |   28000.00 |   35500.00 |   42000.00 |   45500.00 |   55000.00
BARTENDER                           |   30 |   93566.67 |   19687.02 |   57000.00 |   84000.00 |   93000.00 |  100000.00 |  133000.00
BEAUTY ADVISOR                      |   43 |   45116.28 |    6817.25 |   33000.00 |   41000.00 |   46000.00 |   50000.00 |   60000.00
BOILERMAKER                         |   12 |   80250.00 |   11804.84 |   61000.00 |   72250.00 |   77000.00 |   94000.00 |  100000.00
BOOKKEEPER                          |   18 |   58833.33 |   18720.90 |   26000.00 |   54250.00 |   56000.00 |   62500.00 |  121000.00
CLAIMS ADJUSTER                     |   46 |   91804.35 |   10105.14 |   75000.00 |   86000.00 |   90500.00 |   95000.00 |  118000.00
COMPLIANCE OFFICER                  |   58 |  157620.69 |   37687.38 |   82000.00 |  127000.00 |  165000.00 |  186000.00 |  215000.00
CORPORATE COUNSEL                   |  100 |  347990.00 |   65691.78 |  137000.00 |  329000.00 |  352000.00 |  370000.00 |  490000.00
CURRICULUM DEVELOPER                |   34 |  128205.88 |   40086.51 |   67000.00 |  102000.00 |  115500.00 |  146500.00 |  220000.00
DELIVERY DRIVER                     |   26 |   59423.08 |    8656.58 |   45000.00 |   55000.00 |   58000.00 |   65500.00 |   79000.00
DENTAL ASSISTANT                    |   48 |   55458.33 |    6864.64 |   45000.00 |   52750.00 |   55000.00 |   57000.00 |   89000.00
ELECTRICIAN                         |   84 |   97821.43 |   18721.11 |   54000.00 |   82000.00 |  100000.00 |  115000.00 |  130000.00
FOOD SCIENTIST                      |   18 |   90777.78 |    9318.77 |   73000.00 |   84000.00 |   90000.00 |   97000.00 |  110000.00
INSIDE SALES                        |   98 |   92255.10 |   25003.80 |   45000.00 |   75250.00 |   89000.00 |  105000.00 |  150000.00
INSURANCE AGENT                     |   96 |   98802.08 |   26670.68 |   43000.00 |   83000.00 |   95500.00 |  107000.00 |  193000.00
LEGAL SECRETARY                     |   47 |   94914.89 |   16345.77 |   62000.00 |   81000.00 |   95000.00 |  109500.00 |  125000.00
LIBRARIAN                           |   54 |   89259.26 |   17488.82 |   50000.00 |   77000.00 |   87000.00 |  105750.00 |  120000.00
MEDICAL ASSISTANT                   |   97 |   61907.22 |   21973.31 |   35000.00 |   48000.00 |   54000.00 |   70000.00 |  130000.00
MERCHANDISER                        |   95 |   57094.74 |   15860.63 |   35000.00 |   45000.00 |   53000.00 |   61000.00 |   90000.00
NURSE                               |  190 |  133431.58 |   41159.17 |   40000.00 |  100750.00 |  134500.00 |  170000.00 |  220000.00
OFFICE ADMINISTRATOR                |    6 |   51833.33 |   10869.17 |   39000.00 |   43500.00 |   48500.00 |   60250.00 |   69000.00
OUTSIDE SALES                       |  110 |  132545.45 |   44007.57 |   60000.00 |   99250.00 |  124500.00 |  150000.00 |  255000.00
PARALEGAL                           |   44 |   74090.91 |   15351.66 |   43000.00 |   66500.00 |   74500.00 |   80250.00 |  110000.00
PARAMEDIC                           |   22 |   71318.18 |   12941.78 |   59000.00 |   61000.00 |   70000.00 |   72000.00 |  104000.00
POLICE OFFICER                      |   50 |  107260.00 |   24515.15 |   62000.00 |   86000.00 |  102000.00 |  130000.00 |  161000.00
PRINCIPAL                           |   94 |  357648.44 |   87046.26 |  140000.00 |  311250.00 |  389000.00 |  415750.00 |  480000.00
PROGRAM COORDINATOR                 |   81 |   71098.77 |   12766.28 |   49000.00 |   64000.00 |   68000.00 |   80000.00 |   95000.00
REAL ESTATE AGENT                   |  122 |  141942.62 |   21946.77 |   68000.00 |  128000.00 |  147000.00 |  161000.00 |  161000.00
RECRUIT                             |    9 |  141777.78 |   51267.88 |   87000.00 |  100000.00 |  115000.00 |  180000.00 |  229000.00
RETAIL SALES                        |    6 |   63833.33 |   20667.34 |   35000.00 |   44500.00 |   69500.00 |   82500.00 |   86000.00
SALES ASSOCIATE                     |   95 |   58882.27 |   26740.06 |   27000.00 |   42000.00 |   48000.00 |   75000.00 |  145000.00
SCHOOL COUNSELOR                    |   81 |   95123.46 |   23811.18 |   58000.00 |   80000.00 |   88000.00 |  102000.00 |  150000.00
SCHOOL PSYCHOLOGIST                 |  112 |  115625.00 |   23636.43 |   70000.00 |  101750.00 |  114000.00 |  140000.00 |  150000.00
SECURITY OFFICER                    |   99 |   56323.23 |   17347.80 |   28000.00 |   44000.00 |   51000.00 |   70000.00 |   90000.00
SOCIAL WORKER                       |  101 |   98811.88 |   22590.94 |   60000.00 |   78000.00 |   99000.00 |  118000.00 |  132000.00
SUPERVISOR                          |   78 |   72589.74 |   26146.74 |   41000.00 |   62250.00 |   70000.00 |   77000.00 |  258000.00
TALENT ASSISTANT                    |    7 |   53000.00 |   11844.23 |   43000.00 |   46000.00 |   47000.00 |   54500.00 |   80000.00
TAX ADVISOR                         |    5 |   68800.00 |   23794.12 |   48000.00 |   51000.00 |   52000.00 |   85000.00 |  108000.00
TEACHER                             |   96 |   92718.75 |   23685.75 |   45000.00 |   74000.00 |   91000.00 |  114000.00 |  125000.00
TECHNICIAN                          |  207 |   68487.92 |   36299.86 |   35000.00 |   49500.00 |   63000.00 |   82000.00 |  490000.00
THERAPIST                           |   48 |   94687.50 |   15798.41 |   75000.00 |   83750.00 |   91000.00 |  100500.00 |  150000.00
TOURING ASSISTANT                   |    5 |   54200.00 |    7194.44 |   47000.00 |   50000.00 |   50000.00 |   57000.00 |   67000.00
TRANSPORTATION PLANNER              |   77 |   93233.77 |   15113.33 |   65000.00 |   83000.00 |   94000.00 |  105000.00 |  140000.00
UNDERWRITER                         |  107 |  109663.55 |   29885.12 |   43000.00 |   86000.00 |  105000.00 |  140000.00 |  166000.00
URBAN PLANNER                       |   13 |   98461.54 |   20375.76 |   70000.00 |   85000.00 |  100000.00 |  113000.00 |  129000.00
VICE PRESIDENT                      |   61 |  210377.39 |   40338.08 |   91253.00 |  195000.00 |  220000.00 |  229000.00 |  360000.00
WELDER                              |   18 |   66333.33 |    8232.73 |   50000.00 |   59000.00 |   67500.00 |   72500.00 |   79000.00

In [16]:
print("#### OTHER POSITION ################ COUNT ##### AVG ######## STD ######## MIN ######## 25% ######## 50% ######## 75% ######## MAX ####")
for i in range(len(other_positions)):
    print("{:35} | {:4} | {:10.2f} | {:10.2f} | {:10.2f} | {:10.2f} | {:10.2f} | {:10.2f} | {:10.2f}".format(
        other_positions[i].upper(), other_positions_cnt[i], np.array(other_positions_slr[i]).mean(),
        np.array(other_positions_slr[i]).std(), np.array(other_positions_slr[i]).min(),  
        np.percentile(other_positions_slr[i], 25), np.percentile(other_positions_slr[i], 50), 
        np.percentile(other_positions_slr[i], 75), np.array(other_positions_slr[i]).max()))

#### OTHER POSITION ################ COUNT ##### AVG ######## STD ######## MIN ######## 25% ######## 50% ######## 75% ######## MAX ####
ANALYST (OTHER)                     |   51 |  103845.25 |   41884.63 |   31973.00 |   76500.00 |  102000.00 |  120000.00 |  242000.00
DEVELOPER (OTHER)                   |   38 |  140403.79 |   49336.45 |   41491.00 |  105000.00 |  140000.00 |  174500.00 |  278000.00
ENGINEER (OTHER)                    |   60 |  151273.55 |   60114.07 |   43483.00 |  120000.00 |  145000.00 |  179500.00 |  316000.00
SERVER (OTHER)                      |   16 |  102062.50 |   11760.47 |   77000.00 |   93000.00 |  106000.00 |  110500.00 |  120000.00
ASSISTANT (OTHER)                   |   71 |   64200.82 |   37678.32 |   32000.00 |   47000.00 |   54000.00 |   63000.00 |  282000.00

In [17]:
salary_by_position = pd.DataFrame(columns=['Title','Count','Average','Minimum','25thPercent','50thPercent','75thPercent','Maximum'])
for i in range(len(white_collar_positions)):
    salary_row = pd.DataFrame({'Title': [white_collar_positions[i]], 
                  'Count': [white_collar_positions_cnt[i]], 
                  'Average': [np.array(white_collar_positions_slr[i]).mean()], 
                  'Minimum': [np.array(white_collar_positions_slr[i]).min()],
                  '25thPercent': [np.percentile(white_collar_positions_slr[i], 25)], 
                  '50thPercent': [np.percentile(white_collar_positions_slr[i], 50)],
                  '75thPercent': [np.percentile(white_collar_positions_slr[i], 75)],
                  'Maximum': [np.array(white_collar_positions_slr[i]).max()]})
    # salary_by_position = salary_by_position.append(salary_row, ignore_index=True)
    salary_by_position = pd.concat([salary_by_position, salary_row], ignore_index=True)
for i in range(len(blue_collar_positions)):
    salary_row = pd.DataFrame({'Title': [blue_collar_positions[i]], 
                  'Count': [blue_collar_positions_cnt[i]], 
                  'Average': [np.array(blue_collar_positions_slr[i]).mean()], 
                  'Minimum': [np.array(blue_collar_positions_slr[i]).min()],
                  '25thPercent': [np.percentile(blue_collar_positions_slr[i], 25)], 
                  '50thPercent': [np.percentile(blue_collar_positions_slr[i], 50)],
                  '75thPercent': [np.percentile(blue_collar_positions_slr[i], 75)],
                  'Maximum': [np.array(blue_collar_positions_slr[i]).max()]})
    salary_by_position = pd.concat([salary_by_position, salary_row], ignore_index=True)
for i in range(len(other_positions)):
    salary_row = pd.DataFrame({'Title': [other_positions[i]], 
                  'Count': [other_positions_cnt[i]], 
                  'Average': [np.array(other_positions_slr[i]).mean()], 
                  'Minimum': [np.array(other_positions_slr[i]).min()],
                  '25thPercent': [np.percentile(other_positions_slr[i], 25)], 
                  '50thPercent': [np.percentile(other_positions_slr[i], 50)],
                  '75thPercent': [np.percentile(other_positions_slr[i], 75)],
                  'Maximum': [np.array(other_positions_slr[i]).max()]})
    salary_by_position = pd.concat([salary_by_position, salary_row], ignore_index=True)

In [18]:
salary_by_position.head(10)

,Title,Count,Average,Minimum,25thPercent,50thPercent,75thPercent,Maximum
0,Account Manager,20,189300.000000,46000,130000.00,180000.0,258250.0,310000
1,AI Engineer,18,163745.611111,49421,151250.00,163000.0,192000.0,246000
2,Application Engineer / Developer,160,191744.368750,40925,168500.00,195000.0,213750.0,278000
3,Automation Tester,6,106726.333333,70202,84867.00,105500.0,124750.0,150000
4,Backend Developer,18,171555.555556,105000,172000.00,173500.0,184750.0,192000
5,Business Analyst,392,121055.897959,45390,90000.00,113500.0,150000.0,265000
6,Business Intelligence Eng. / Dev.,167,184679.155689,70706,174000.00,185000.0,205000.0,235000
7,Chemical Engineer,41,111951.219512,77000,88000.00,107000.0,135000.0,182000
8,Civil Engineer,215,115093.023256,75000,95000.00,110000.0,134000.0,178000
9,Cloud Engineer,18,127430.611111,38397,88926.25,106984.5,177750.0,220000

In [19]:
salary_by_position.tail(10)

,Title,Count,Average,Minimum,25thPercent,50thPercent,75thPercent,Maximum
124,Transportation Planner,77,93233.766234,65000,83000.0,94000.0,105000.0,140000
125,Underwriter,107,109663.551402,43000,86000.0,105000.0,140000.0,166000
126,Urban Planner,13,98461.538462,70000,85000.0,100000.0,113000.0,129000
127,Vice President,61,210377.393443,91253,195000.0,220000.0,229000.0,360000
128,Welder,18,66333.333333,50000,59000.0,67500.0,72500.0,79000
129,Analyst (Other),51,103845.254902,31973,76500.0,102000.0,120000.0,242000
130,Developer (Other),38,140403.789474,41491,105000.0,140000.0,174500.0,278000
131,Engineer (Other),60,151273.550000,43483,120000.0,145000.0,179500.0,316000
132,Server (Other),16,102062.500000,77000,93000.0,106000.0,110500.0,120000
133,Assistant (Other),71,64200.816901,32000,47000.0,54000.0,63000.0,282000

In [20]:
salary_by_position.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Title        134 non-null    object
 1   Count        134 non-null    object
 2   Average      134 non-null    float64
 3   Minimum      134 non-null    object
 4   25thPercent  134 non-null    float64
 5   50thPercent  134 non-null    float64
 6   75thPercent  134 non-null    float64
 7   Maximum      134 non-null    object
dtypes: float64(4), object(4)
memory usage: 8.5+ KB

In [21]:
salary_by_position.to_csv('salaries_by_position.csv')